// Sheet data extracted from HTML files
// This centralizes all the table data for the sheets

export interface SheetData {
  id: string;
  title: string;
  description: string;
  rows: number;
  columns: number;
  headers: string[];
  data: string[][];
}

export const SHEETS_DATA: Record<string, SheetData> = {
  'block-master': {
    id: 'block-master',
    title: 'Block_Master',
    description: 'Krishnagiri block-wise master. Soil-property fields are dominant block-level estimates.',
    rows: 10,
    columns: 20,
    headers: ['Block', 'Representative villages', 'Major crops', 'Horticulture strength', 'Irrigation pattern', 'Dominant soil groups', 'Texture class', 'Approx sand %', 'Approx silt %', 'Approx clay %', 'Structure', 'Color', 'Porosity', 'Water-holding capacity', 'pH', 'Organic matter', 'CEC', 'Salinity', 'Soil nutrient deficiencies', 'Practical note'],
    data: [
      ['Hosur', 'Achettipalli; Bagaloor; Belathur; Chennasandiram; Kelavarapalli; Onnalvadi; Thorapalli Agraharam; Thummanapalli', 'Vegetables, flowers, mango, fodder, banana, some maize and pulses', 'Very High', 'Open wells, borewells, farm ponds, some tank support', 'Red sandy loam, red loam, gravelly upland soils', 'Sandy loam to red loam', '55-70', '10-20', '15-25', 'Weak granular to sub-angular blocky', 'Red to reddish brown', 'Moderate to high', 'Low to moderate', '6.8-7.8 (can move higher under alkaline irrigation)', 'Low to medium', 'Low to moderate', 'Usually low inland', 'N, P, Zn, B; Fe in calcareous/alkaline pockets', 'Fast-draining, fertigation-responsive, highly suitable for vegetables/flowers but needs split nutrition and micronutrient correction.'],
      ['Shoolagiri', 'Athimugam; Berigai; Kumbalam; Marandapalli; Pannapalli; Shoolagiri; Uddanapalli', 'Tomato, beans, cabbage, flowers, mango, pulses, maize in irrigated pockets', 'Very High', 'Borewells/open wells with supplemental tank water in places', 'Red sandy loam, red loam, gravelly red uplands, some lateritic influence', 'Sandy loam to loam', '55-68', '10-18', '18-27', 'Weak blocky; loose in gravelly sites', 'Red, dark red, red-brown', 'Moderate', 'Low to moderate effective WHC', '6.5-7.8', 'Low to medium', 'Low to moderate', 'Usually low', 'N, P, Zn, B; sometimes Fe in high-pH spots', 'Intensive vegetable/flower production. Highly responsive to balanced fertigation and crop protection.'],
      ['Thally', 'Ballavaram; Berkundam; Chikkadasarahalli; Jawalagiri; Thandalam; Thally; Urigam', 'Vegetables, flowers, mango, pulses, millets in rainfed pockets', 'High', 'Open wells, borewells, check dams; variable coverage', 'Red loam, hill soils, lateritic gravelly patches', 'Loam to sandy clay loam', '45-60', '15-25', '22-30', 'Moderate blocky; variable by slope', 'Dark red to brown', 'Moderate', 'Moderate', '6.0-7.2', 'Low to moderate', 'Moderate', 'Low', 'N, Zn, B, Fe on lateritic/gravelly slopes', 'Variable terrain demands customized advisory. Mix of highland horticulture and rainfed crops.'],
      ['Kaveripattinam', 'Alambadi; Arasampalayam; Bedarahalli; Denkanikottai; Kaveripattinam; Nagamangalam', 'Vegetables, flowers, maize, pulses, mango, limited banana', 'High', 'Borewells, tanks, open wells; mixed coverage', 'Red loam, sandy loam, some clay-dominant pockets', 'Sandy loam to loam', '50-65', '12-22', '18-28', 'Sub-angular blocky to granular', 'Red-brown to dark brown', 'Moderate', 'Low to moderate', '6.5-7.5', 'Low to medium', 'Moderate', 'Low', 'N, P, Zn, B; Mn occasionally', 'Irrigation-variable block. Good for irrigated vegetables/flowers but needs targeted moisture management.'],
      ['Denkanikottai', 'Andigoundanur; Bilikundlu; Jalagondapuram; Kelamangalam; Anchetty', 'Pulses, groundnut, millets, mango, scattered vegetables', 'Moderate', 'Tanks, some borewells, limited open wells', 'Red sandy loam, gravelly uplands, some laterite', 'Sandy loam to clay loam', '48-60', '15-20', '22-32', 'Blocky; crusting on exposed slopes', 'Red to pale brown', 'Moderate', 'Low to moderate', '6.2-7.2', 'Low', 'Low to moderate', 'Low', 'N, P, Zn, B, S; Fe in laterite areas', 'Mixed dryland and irrigated pockets. Focus on dryland pulses, millets, seasonal groundnut.'],
      ['Bargur', 'Alasapalli; Bargur; Kandikuppam; Mittahalli; Rayakottai', 'Millets, pulses, groundnut, mango, some vegetables where irrigated', 'Moderate', 'Tanks, limited borewells, seasonal streams', 'Red gravelly loam, lateritic soils, black soil patches', 'Sandy clay loam to clay loam', '40-55', '15-22', '25-35', 'Blocky to massive', 'Red-brown to dark', 'Moderate to low', 'Moderate', '6.0-7.5', 'Low', 'Moderate', 'Low', 'N, P, Zn, B, S; Fe and Mn in gravelly areas', 'Rainfed-dominated block. Seasonal millet and pulse focus with supplemental horticulture in irrigated villages.'],
      ['Mathur', 'Athur; Kovilur; Mathur; Puliyanur; Solur', 'Ragi, pulses, groundnut, millets, limited vegetables', 'Low to Moderate', 'Tanks, check dams, limited wells', 'Red loam, sandy loam, gravelly red soils', 'Sandy loam to loam', '50-65', '12-18', '20-28', 'Weak blocky to granular', 'Red to pale red-brown', 'Moderate', 'Low to moderate', '6.5-7.4', 'Low', 'Low to moderate', 'Low', 'N, P, Zn, B; sometimes S', 'Predominantly rainfed. Focus on dryland crops with selective fertigation support in irrigated pockets.'],
      ['Kelamangalam', 'Agraharam; Kelamangalam; Madenahalli; Nallur; Ponnandahalli', 'Millets, groundnut, pulses, fodder, limited horticulture', 'Low', 'Tanks, limited wells, rainfed dominant', 'Red sandy loam, gravelly uplands, clay loam pockets', 'Sandy loam to sandy clay loam', '48-58', '14-20', '24-32', 'Blocky; surface crusting common', 'Red to dark red', 'Moderate to low', 'Low to moderate', '6.4-7.3', 'Low', 'Low to moderate', 'Low', 'N, P, Zn, B, S', 'Dryland-focused block. Limited irrigation for horticulture; rainfed pulse and millet strategy.'],
      ['Pennagaram', 'Kamandoddi; Kondappanayanapalli; Pennagaram; Pottipalli; Sathghar', 'Millets, groundnut, pulses, limited irrigated crops', 'Low', 'Tanks, rainfed dominant, few wells', 'Red gravelly loam, sandy loam, some clay patches', 'Sandy loam to clay loam', '45-58', '15-20', '25-33', 'Blocky; crusting and compaction on clay patches', 'Red-brown to dark', 'Low to moderate', 'Low to moderate', '6.2-7.4', 'Low', 'Low', 'Low', 'N, P, Zn, B, S, Mn', 'Rainfed-predominant block. Focus on dryland crops, seasonal groundnut, and millets.'],
      ['Uthangarai', 'Anchetty; Dinnur; Palacode; Santhur; Uthangarai', 'Ragi, groundnut, pulses, millets, limited vegetables', 'Low', 'Tanks, seasonal streams, limited wells', 'Red sandy loam, gravelly red loam, clay pockets', 'Sandy loam to clay loam', '45-55', '15-22', '26-35', 'Blocky; some compaction', 'Red to dark brown', 'Low to moderate', 'Low to moderate', '6.0-7.2', 'Low', 'Low', 'Low', 'N, P, Zn, B, S', 'Rainfed block with limited irrigation. Focus on dryland cereals and pulses.'],
    ],
  },
  'cluster-master': {
    id: 'cluster-master',
    title: 'Cluster_Master',
    description: 'Krishnagiri true village cluster map master. Clustering is by production system, soil behavior, irrigation logic, crop pattern, and agri-input business relevance.',
    rows: 6,
    columns: 14,
    headers: ['Cluster', 'Micro-cluster label', 'District logic', 'Soil logic', 'Irrigation logic', 'Dominant crops', 'Key risks', 'Priority input categories', 'Crop diversity score', 'Input intensity score', 'Irrigation security score', 'Market access score', 'Soil constraint score', 'Nutrient risk score'],
    data: [
      ['Urban_Horticulture_Belt', 'Urban-linked vegetable-flower cluster', 'Hosur urban influence, market-linked peri-urban horticulture', 'Red sandy loam / red loam; quick-draining; fertigation responsive', 'Borewell + well + farm pond + drip', 'Vegetables, flowers, banana, fodder, mango', 'Water quality shift, high nutrient mining, labour and market volatility', 'WSF, micronutrients, biostimulants, crop protection, drip accessories', '5', '5', '4', '5', '3', '4'],
      ['Flower_Vegetable_Intensive_Belt', 'Intensive flower and vegetable production cluster', 'Hosur-Shoolagiri commercial horticulture strip', 'Red loam to gravelly red loam; moderate WHC, recurrent micronutrient demand', 'Borewell/open well with drip and micro-irrigation', 'Tomato, beans, cabbage, flowers, vegetables, mango', 'Thrips/mites/disease pressure, price crash, nutrient imbalance', 'Crop protection, WSF, Ca-B, Zn-B, adjuvants, biostimulants', '5', '5', '4', '4', '3', '5'],
      ['Highland_Horticulture_Belt', 'High-elevation horticulture and cool-belt cluster', 'Thally highlands and adjoining elevated belts', 'Red loam, hill soil, lateritic/gravelly patches; variable depth', 'Wells, streams, check dams, localized drip', 'Vegetables, flowers, mango, minor millets, pulses', 'Erosion, shallow depth, uneven irrigation, weather variability', 'Water-solubles, micronutrients, organics, fungicides', '4', '4', '3', '3', '4', '4'],
      ['Mango_Orchard_Belt', 'Mango-dominant orchard and intercrop cluster', 'Denkanikottai, Bargur, and mango-orchard villages', 'Red loam to gravelly loam; moderate depth; variable fertility', 'Tanks, wells, check dams; semi-irrigated', 'Mango, intercrop pulses, groundnut, millets', 'Fruit-fly, anthracnose, irregular bearing, market access', 'Micronutrients, orchard nutrition, biostimulants, protection', '3', '3', '3', '2', '3', '3'],
      ['Mixed_Dryland_Belt', 'Rainfed dryland crop cluster', 'Kelamangalam, Pennagaram, Uthangarai, and surrounding rainfed areas', 'Red gravelly loam, sandy loam, clay pockets; variable WHC', 'Tanks, seasonal streams, limited wells', 'Ragi, millets, pulses, groundnut', 'Rainfall variability, moisture stress, low returns', 'Basal fertilizers, seed treatment, herbicides', '3', '2', '2', '2', '4', '3'],
      ['Irrigated_Mixed_Belt', 'Irrigated mixed-crop cluster', 'Kaveripattinam and adjoining irrigated pockets', 'Red loam, sandy loam, mixed soils; moderate depth', 'Borewells, tanks, open wells; mixed coverage', 'Vegetables, maize, pulses, fodder, limited mango', 'Irrigation variability, soil fatigue, market volatility', 'Balanced NPK, micronutrients, crop protection', '4', '3', '3', '3', '3', '3'],
    ],
  },
  'read-me': {
    id: 'read-me',
    title: 'Read_Me',
    description: 'Krishnagiri IGIM workbook with block-wise and representative village-wise planning sheets.',
    rows: 10,
    columns: 2,
    headers: ['Section', 'Description'],
    data: [
      ['Purpose', 'This workbook is the operational IGIM planning resource for Krishnagiri district, covering block-wise and representative village-wise data.'],
      ['Block_Master', 'Block-level master with dominant soil properties, major crops, irrigation patterns, and practical field notes.'],
      ['Village_Master', 'Village-wise planning sheet with inherited block-level generalizations for representative villages.'],
      ['Cluster_Master', 'True village cluster map master based on production system, soil behavior, irrigation, and agri-input business relevance.'],
      ['Scoring Sheets', 'Village and cluster scoring sheets for business prioritization and opportunity sizing.'],
      ['Crop Sheets', 'Crop-cluster matrix and summary sheets for product planning and campaign targeting.'],
      ['Maps', 'Interactive route maps for cluster beat planning and field visit execution.'],
      ['Data Sources', 'Secondary data, block-level field validation, and IGIM domain expertise.'],
      ['Usage', 'Field staff daily reference, retail planning support, and management review.'],
      ['Updates', 'This workbook is updated periodically as field validation expands.'],
    ],
  },
  'village-master': {
    id: 'village-master',
    title: 'Village_Master',
    description: 'Village-wise planning sheet for Krishnagiri. Values are inherited block-level generalizations for representative villages.',
    rows: 72,
    columns: 23,
    headers: ['Block', 'Village', 'Village coverage type', 'Village profile tag', 'Major crops / business focus', 'Horticulture strength', 'Irrigation pattern', 'Dominant soil groups', 'Texture class', 'Approx sand %', 'Approx silt %', 'Approx clay %', 'Structure', 'Color', 'Porosity', 'Water-holding capacity', 'pH', 'Organic matter', 'CEC', 'Salinity', 'Soil nutrient deficiencies', 'Practical village note', 'Inherited block rationale'],
    data: [
      ['Hosur', 'Achettipalli', 'Representative village planning row', 'Urban-linked horticulture / vegetables / flowers', 'Vegetables, flowers, mango, fodder, banana, some maize and pulses', 'Very High', 'Open wells, borewells, farm ponds, some tank support', 'Red sandy loam, red loam, gravelly upland soils', 'Sandy loam to red loam', '55-70', '10-20', '15-25', 'Weak granular to sub-angular blocky', 'Red to reddish brown', 'Moderate to high', 'Low to moderate', '6.8-7.8', 'Low to medium', 'Low to moderate', 'Usually low inland', 'N, P, Zn, B; Fe in calcareous/alkaline pockets', 'Representative village row for planning. Soil and nutrient values follow dominant Hosur block conditions.', 'Inherited from Hosur block for sales planning and advisory clustering.'],
      ['Hosur', 'Bagaloor', 'Representative village planning row', 'Urban-linked horticulture / vegetables / flowers', 'Vegetables, flowers, mango, fodder, banana, some maize and pulses', 'Very High', 'Open wells, borewells, farm ponds, some tank support', 'Red sandy loam, red loam, gravelly upland soils', 'Sandy loam to red loam', '55-70', '10-20', '15-25', 'Weak granular to sub-angular blocky', 'Red to reddish brown', 'Moderate to high', 'Low to moderate', '6.8-7.8', 'Low to medium', 'Low to moderate', 'Usually low inland', 'N, P, Zn, B; Fe in calcareous/alkaline pockets', 'Representative village row for planning.', 'Inherited from Hosur block.'],
      ['Hosur', 'Belathur', 'Representative village planning row', 'Urban-linked horticulture / vegetables / flowers', 'Vegetables, flowers, mango, fodder, banana, some maize and pulses', 'Very High', 'Open wells, borewells, farm ponds, some tank support', 'Red sandy loam, red loam, gravelly upland soils', 'Sandy loam to red loam', '55-70', '10-20', '15-25', 'Weak granular to sub-angular blocky', 'Red to reddish brown', 'Moderate to high', 'Low to moderate', '6.8-7.8', 'Low to medium', 'Low to moderate', 'Usually low inland', 'N, P, Zn, B; Fe in calcareous/alkaline pockets', 'Representative village row for planning.', 'Inherited from Hosur block.'],
      ['Shoolagiri', 'Athimugam', 'Representative village planning row', 'Intensive horticulture / vegetables / flowers', 'Tomato, beans, cabbage, flowers, mango, pulses, maize', 'Very High', 'Borewells/open wells with supplemental tank water', 'Red sandy loam, red loam, gravelly red uplands', 'Sandy loam to loam', '55-68', '10-18', '18-27', 'Weak blocky; loose in gravelly sites', 'Red, dark red, red-brown', 'Moderate', 'Low to moderate effective WHC', '6.5-7.8', 'Low to medium', 'Low to moderate', 'Usually low', 'N, P, Zn, B; sometimes Fe in high-pH spots', 'Representative village row for Shoolagiri block.', 'Inherited from Shoolagiri block.'],
      ['Shoolagiri', 'Berigai', 'Representative village planning row', 'Intensive horticulture / vegetables / flowers', 'Tomato, beans, cabbage, flowers, mango, pulses, maize', 'Very High', 'Borewells/open wells with supplemental tank water', 'Red sandy loam, red loam, gravelly red uplands', 'Sandy loam to loam', '55-68', '10-18', '18-27', 'Weak blocky; loose in gravelly sites', 'Red, dark red, red-brown', 'Moderate', 'Low to moderate effective WHC', '6.5-7.8', 'Low to medium', 'Low to moderate', 'Usually low', 'N, P, Zn, B; sometimes Fe in high-pH spots', 'Representative village row for Shoolagiri block.', 'Inherited from Shoolagiri block.'],
      ['Thally', 'Ballavaram', 'Representative village planning row', 'Highland horticulture', 'Vegetables, flowers, mango, pulses, millets', 'High', 'Open wells, borewells, check dams', 'Red loam, hill soils, lateritic gravelly patches', 'Loam to sandy clay loam', '45-60', '15-25', '22-30', 'Moderate blocky; variable by slope', 'Dark red to brown', 'Moderate', 'Moderate', '6.0-7.2', 'Low to moderate', 'Moderate', 'Low', 'N, Zn, B, Fe on lateritic/gravelly slopes', 'Representative village row for Thally block.', 'Inherited from Thally block.'],
    ],
  },
  'crop-cluster-matrix': {
    id: 'crop-cluster-matrix',
    title: 'Crop_Cluster_Matrix',
    description: 'Village-wise crops mapped to clusters for planning purposes.',
    rows: 74,
    columns: 4,
    headers: ['Village', 'Block', 'Cluster', 'Primary Crops'],
    data: [
      ['Achettipalli', 'Hosur', 'Urban_Horticulture_Belt', 'Vegetables, flowers, banana, mango'],
      ['Bagaloor', 'Hosur', 'Urban_Horticulture_Belt', 'Vegetables, flowers, banana, mango'],
      ['Belathur', 'Hosur', 'Urban_Horticulture_Belt', 'Vegetables, flowers, mango'],
      ['Athimugam', 'Shoolagiri', 'Flower_Vegetable_Intensive_Belt', 'Tomato, beans, flowers, cabbage'],
      ['Berigai', 'Shoolagiri', 'Flower_Vegetable_Intensive_Belt', 'Tomato, beans, flowers, cabbage'],
      ['Ballavaram', 'Thally', 'Highland_Horticulture_Belt', 'Vegetables, flowers, mango, pulses'],
    ],
  },
  'crop-cluster-summary': {
    id: 'crop-cluster-summary',
    title: 'Crop_Cluster_Summary',
    description: 'Summary of crop patterns by cluster for commercial planning.',
    rows: 8,
    columns: 5,
    headers: ['Cluster', 'Villages', 'Primary Crops', 'Key Products', 'Business Focus'],
    data: [
      ['Urban_Horticulture_Belt', '8', 'Vegetables, flowers, banana, mango', 'WSF, micronutrients, crop protection', 'High-frequency premium sales'],
      ['Flower_Vegetable_Intensive_Belt', '6', 'Tomato, beans, cabbage, flowers', 'Crop protection, WSF, Ca-B, Zn-B', 'Campaign + technical sales'],
      ['Highland_Horticulture_Belt', '10', 'Vegetables, flowers, mango, pulses', 'WSF, micronutrients, organics', 'Specialty horticulture support'],
      ['Mango_Orchard_Belt', '18', 'Mango, pulses, groundnut, millets', 'Micronutrients, orchard nutrition', 'Seasonal orchard campaign'],
      ['Mixed_Dryland_Belt', '18', 'Ragi, millets, pulses, groundnut', 'Basal fertilizers, seed treatment', 'Rainfed campaign-based'],
      ['Irrigated_Mixed_Belt', '12', 'Vegetables, maize, pulses, fodder', 'Balanced NPK, micronutrients', 'Balanced multi-crop dealer'],
    ],
  },
  'cluster-opportunity': {
    id: 'cluster-opportunity',
    title: 'Cluster_Opportunity',
    description: 'Commercial opportunity analysis by cluster.',
    rows: 8,
    columns: 10,
    headers: ['Cluster', 'Villages', 'Input Intensity', 'Risk Score', 'Market Access', 'Channel Strategy', 'Priority Season', 'Product Focus', 'Dealer Opportunity', 'Remarks'],
    data: [
      ['Urban_Horticulture_Belt', '8', '4.4', '3.5', '5', 'Advisory-led premium dealer', 'Round-year + flush campaigns', 'WSF, micronutrients, protection', 'High', 'Fast-repeat, high-service cluster'],
      ['Flower_Vegetable_Intensive_Belt', '6', '4.5', '3.6', '4', 'Campaign + technical sales', 'Peak vegetable + flower windows', 'Crop protection, WSF, Ca-B', 'High', 'Highest crop-protection pull'],
      ['Highland_Horticulture_Belt', '10', '3.9', '3.2', '3', 'Specialty horticulture support', 'Cool-belt windows', 'WSF, micronutrients, organics', 'Medium-High', 'Quality-focused, moderate market access'],
      ['Mango_Orchard_Belt', '18', '2.7', '2.2', '2', 'Seasonal orchard campaign', 'Pre-flowering to fruit development', 'Micronutrients, orchard nutrition', 'Medium', 'Seasonal but strategic cluster'],
      ['Mixed_Dryland_Belt', '18', '2.7', '2.3', '2', 'Rainfed campaign-based', 'Kharif-focused', 'Basal fertilizers, seed treatment', 'Low-Medium', 'Price-sensitive, volume focus'],
      ['Irrigated_Mixed_Belt', '12', '3.4', '2.8', '3', 'Balanced multi-crop dealer', 'Year-round with peaks', 'Balanced NPK, micronutrients', 'Medium', 'Diverse, stable demand'],
    ],
  },
  'cluster-product-priority': {
    id: 'cluster-product-priority',
    title: 'Cluster_Product_Priority',
    description: 'Product priority ranking by cluster for stocking decisions.',
    rows: 8,
    columns: 8,
    headers: ['Cluster', 'Priority 1', 'Priority 2', 'Priority 3', 'Priority 4', 'Priority 5', 'Notes', 'Stocking Strategy'],
    data: [
      ['Urban_Horticulture_Belt', 'WSF (19:19:19, 13:40:13)', 'Micronutrients (Zn, B, Ca-B)', 'Crop protection (fungicides, insecticides)', 'Biostimulants', 'Drip accessories', 'High-frequency premium segment', 'Full range, premium focus'],
      ['Flower_Vegetable_Intensive_Belt', 'Crop protection (thrips/mite control)', 'WSF (Ca-B, Zn-B)', 'Adjuvants', 'Biostimulants', 'Micronutrients', 'Campaign-driven, pest pressure high', 'Protection-heavy stocking'],
      ['Highland_Horticulture_Belt', 'WSF (balanced grades)', 'Micronutrients', 'Organics', 'Fungicides', 'Biostimulants', 'Quality-focused, moderate volumes', 'Specialty horticulture range'],
      ['Mango_Orchard_Belt', 'Micronutrients (orchard grades)', 'Biostimulants', 'Orchard protection', 'Basal NPK', 'Flowering boosters', 'Seasonal peaks, strategic stock', 'Seasonal orchard packs'],
      ['Mixed_Dryland_Belt', 'Basal fertilizers (DAP, urea)', 'Seed treatment', 'Herbicides', 'Micronutrients', 'Wetting agents', 'Price-sensitive, volume focus', 'Basal-heavy, campaign packs'],
      ['Irrigated_Mixed_Belt', 'Balanced NPK', 'Micronutrients', 'Crop protection', 'WSF', 'Biostimulants', 'Diverse demand, stable market', 'Balanced multi-crop range'],
    ],
  },
  'village-scoring': {
    id: 'village-scoring',
    title: 'Village_Scoring',
    description: 'Village-wise business scoring and prioritization.',
    rows: 74,
    columns: 12,
    headers: ['Village', 'Block', 'Cluster', 'Crop Diversity', 'Input Intensity', 'Irrigation Security', 'Market Access', 'Soil Constraint', 'Nutrient Risk', 'Overall Score', 'Priority', 'Remarks'],
    data: [
      ['Achettipalli', 'Hosur', 'Urban_Horticulture_Belt', '5', '5', '4', '5', '3', '4', '4.3', 'High', 'Urban-linked premium horticulture'],
      ['Bagaloor', 'Hosur', 'Urban_Horticulture_Belt', '5', '5', '4', '5', '3', '4', '4.3', 'High', 'Urban-linked premium horticulture'],
      ['Athimugam', 'Shoolagiri', 'Flower_Vegetable_Intensive_Belt', '5', '5', '4', '4', '3', '5', '4.3', 'High', 'Intensive vegetable/flower production'],
      ['Ballavaram', 'Thally', 'Highland_Horticulture_Belt', '4', '4', '3', '3', '4', '4', '3.7', 'Medium-High', 'Highland horticulture, variable terrain'],
    ],
  },
  'igim-scoring': {
    id: 'igim-scoring',
    title: 'IGIM_Scoring',
    description: 'IGIM comprehensive scoring methodology.',
    rows: 15,
    columns: 6,
    headers: ['Dimension', 'Parameter', 'Score Range', 'Weight', 'Description', 'Data Source'],
    data: [
      ['Crop', 'Crop Diversity', '1-5', '15%', 'Number and value of crops grown in the area', 'Field survey + secondary data'],
      ['Input', 'Input Intensity', '1-5', '20%', 'Level of agri-input usage and sophistication', 'Dealer feedback + field observation'],
      ['Irrigation', 'Irrigation Security', '1-5', '15%', 'Reliability and coverage of irrigation infrastructure', 'Block records + field validation'],
      ['Market', 'Market Access', '1-5', '15%', 'Proximity and quality of market linkages', 'Distance + infrastructure assessment'],
      ['Soil', 'Soil Constraint', '1-5', '15%', 'Soil limitations for crop production (inverse scoring)', 'Soil maps + field observation'],
      ['Nutrient', 'Nutrient Risk', '1-5', '20%', 'Deficiency prevalence and correction needs', 'Lab data + field indicators'],
    ],
  },
  'soil-guide': {
    id: 'soil-guide',
    title: 'Soil_Guide',
    description: 'Soil interpretation and management guide.',
    rows: 12,
    columns: 8,
    headers: ['Soil Type', 'Texture', 'WHC', 'pH Range', 'Key Deficiencies', 'Crop Suitability', 'Management', 'Fertigation Response'],
    data: [
      ['Red Sandy Loam', 'Sandy loam', 'Low', '6.5-7.5', 'N, P, Zn, B', 'Vegetables, flowers, mango', 'Split application, frequent fertigation', 'Excellent'],
      ['Red Loam', 'Loam', 'Low-Moderate', '6.5-7.8', 'N, P, Zn, B, Fe', 'Vegetables, flowers, pulses', 'Balanced nutrition, micronutrient correction', 'Good'],
      ['Gravelly Red Loam', 'Sandy loam to loam', 'Low', '6.0-7.5', 'N, Zn, B, Fe, Mn', 'Vegetables, flowers, millets', 'Organic matter addition, split nutrition', 'Good'],
      ['Lateritic Soil', 'Sandy clay loam', 'Low-Moderate', '5.5-6.8', 'N, P, Ca, Mg, Zn, B', 'Millets, pulses, mango', 'Lime if needed, organic matter, micronutrients', 'Moderate'],
      ['Clay Loam', 'Clay loam', 'Moderate-High', '6.0-7.5', 'N, Zn, Fe', 'Pulses, millets, fodder', 'Drainage management, avoid waterlogging', 'Moderate'],
      ['Hill Soil', 'Variable', 'Variable', '5.5-7.0', 'N, P, K, micronutrients', 'Vegetables, flowers, spices', 'Erosion control, organic matter, split application', 'Variable'],
    ],
  },
  'village-cluster-map': {
    id: 'village-cluster-map',
    title: 'Village_Cluster_Map',
    description: 'Village to cluster mapping reference.',
    rows: 74,
    columns: 3,
    headers: ['Village', 'Block', 'Cluster'],
    data: [
      ['Achettipalli', 'Hosur', 'Urban_Horticulture_Belt'],
      ['Bagaloor', 'Hosur', 'Urban_Horticulture_Belt'],
      ['Belathur', 'Hosur', 'Urban_Horticulture_Belt'],
      ['Athimugam', 'Shoolagiri', 'Flower_Vegetable_Intensive_Belt'],
      ['Berigai', 'Shoolagiri', 'Flower_Vegetable_Intensive_Belt'],
      ['Ballavaram', 'Thally', 'Highland_Horticulture_Belt'],
    ],
  },
  'sources': {
    id: 'sources',
    title: 'Sources',
    description: 'Data sources and references.',
    rows: 8,
    columns: 3,
    headers: ['Category', 'Source', 'Notes'],
    data: [
      ['Soil Data', 'District soil survey reports, NBSS&LUP', 'Block-level dominant soil generalizations'],
      ['Crop Data', 'Agriculture department, field surveys', 'Block and village level crop patterns'],
      ['Irrigation', 'Block records, PWD, field observation', 'Tank, well, borewell distribution'],
      ['Market', 'APMC data, trader surveys', 'Market linkages and access assessment'],
      ['Scoring', 'IGIM methodology', 'Composite scoring for business prioritization'],
      ['Validation', 'Field visits, dealer feedback', 'Ground-truthing and local validation'],
    ],
  },
  'village-refs': {
    id: 'village-refs',
    title: 'Village_Refs',
    description: 'Village reference and administrative information.',
    rows: 74,
    columns: 5,
    headers: ['Village', 'Block', 'Taluk', 'Pin Code', 'Reference Type'],
    data: [
      ['Achettipalli', 'Hosur', 'Hosur', '635109', 'Representative village'],
      ['Bagaloor', 'Hosur', 'Hosur', '635109', 'Representative village'],
      ['Belathur', 'Hosur', 'Hosur', '635109', 'Representative village'],
      ['Athimugam', 'Shoolagiri', 'Hosur', '635115', 'Representative village'],
      ['Berigai', 'Shoolagiri', 'Hosur', '635115', 'Representative village'],
      ['Ballavaram', 'Thally', 'Hosur', '635118', 'Representative village'],
    ],
  },
  'cluster-map-view': {
    id: 'cluster-map-view',
    title: 'Cluster_Map_View',
    description: 'Cluster mapping and geographic distribution.',
    rows: 6,
    columns: 5,
    headers: ['Cluster', 'Primary Blocks', 'Villages Count', 'Geographic Span', 'Access Route'],
    data: [
      ['Urban_Horticulture_Belt', 'Hosur', '8', 'Hosur town periphery', 'NH44, SH17'],
      ['Flower_Vegetable_Intensive_Belt', 'Shoolagiri, Hosur', '6', 'Hosur-Shoolagiri corridor', 'NH44, local roads'],
      ['Highland_Horticulture_Belt', 'Thally', '10', 'Thally highlands', 'SH17, hill roads'],
      ['Mango_Orchard_Belt', 'Denkanikottai, Bargur', '18', 'Eastern belt', 'Local roads, interior'],
      ['Mixed_Dryland_Belt', 'Kelamangalam, Pennagaram, Uthangarai', '18', 'Western rainfed belt', 'District roads'],
      ['Irrigated_Mixed_Belt', 'Kaveripattinam', '12', 'Central irrigated pockets', 'SH roads, local'],
    ],
  },
};

export function getSheetData(id: string): SheetData | undefined {
  return SHEETS_DATA[id];
}
