export interface SheetData {
  title: string;
  description: string;
  headers: string[];
  rows: string[][];
}

export const sheetData: Record<string, SheetData> = {
  "read-me": {
    title: "Read_Me",
    description: "Krishnagiri IGIM workbook with block-wise and representative village-wise planning sheets.",
    headers: ["Purpose", "Block-wise IGIM reference for Krishnagiri covering blocks, representative villages, crop patterns, generalized soil properties, and input/dealer scoring."],
    rows: [
      ["Important caveat", "Sand:Silt:Clay ratios, pH, OC, CEC and deficiency fields are block-level dominant-soil estimates, not plot-level lab values. Use soil testing before prescription."],
      ["Best use", "Territory planning, horticulture targeting, crop-input stocking, micronutrient planning, drip/fertigation opportunity mapping."],
      ["Sources", "Official Krishnagiri block/village list; TNAU Krishnagiri district plan; Krishnagiri horticulture page; district export action plan; district soil fertility publication."],
      ["New in this version", ""],
      ["This workbook now includes a true village cluster map for Krishnagiri using six practical production-system clusters: Urban_Horticulture_Belt, Flower_Vegetable_Intensive_Belt, Highland_Horticulture_Belt, Mango_Orchard_Belt, Mixed_Dryland_Belt, and Irrigated_Valley_Mixed_Belt.", ""],
      ["Use Village_Cluster_Map for village targeting, Cluster_Opportunity for portfolio planning, and Cluster_Map_View for block-level planning summary.", ""],
      ["Added upgrade:", ""],
      ["Crop_Cluster_Matrix", "Maps Krishnagiri clusters to priority crops, fit, risk, repeat demand, and product buckets."],
      ["Cluster_Product_Priority", "Scores each cluster by input category relevance for stocking and campaign planning."],
      ["Crop_Cluster_Summary", "Commercial summary sheet for quick cluster prioritization."],
    ],
  },
  "block-master": {
    title: "Block_Master",
    description: "Krishnagiri block-wise master. Soil-property fields are dominant block-level estimates.",
    headers: ["Block", "Representative villages", "Major crops", "Horticulture strength", "Irrigation pattern", "Dominant soil groups", "Texture class", "Approx sand %", "Approx silt %", "Approx clay %", "Structure", "Color", "Porosity", "Water-holding capacity", "pH", "Organic matter", "CEC", "Salinity", "Soil nutrient deficiencies", "Practical note"],
    rows: [
      ["Hosur", "Achettipalli; Bagaloor; Belathur; Chennasandiram; Kelavarapalli; Onnalvadi; Thorapalli Agraharam; Thummanapalli", "Vegetables, flowers, mango, fodder, banana, some maize and pulses", "Very High", "Open wells, borewells, farm ponds, some tank support", "Red sandy loam, red loam, gravelly upland soils", "Sandy loam to red loam", "55-70", "10-20", "15-25", "Weak granular to sub-angular blocky", "Red to reddish brown", "Moderate to high", "Low to moderate", "6.8-7.8", "Low to medium", "Low to moderate", "Usually low inland", "N, P, Zn, B; Fe in calcareous/alkaline pockets", "Fast-draining, fertigation-responsive, highly suitable for vegetables/flowers but needs split nutrition and micronutrient correction."],
      ["Shoolagiri", "Athimugam; Berigai; Kumbalam; Marandapalli; Pannapalli; Shoolagiri; Uddanapalli", "Tomato, beans, cabbage, flowers, mango, pulses, maize in irrigated pockets", "Very High", "Borewells/open wells with supplemental tank water in places", "Red sandy loam, red loam, gravelly red uplands, some lateritic influence", "Sandy loam to loam", "55-68", "10-18", "18-27", "Weak blocky; loose in gravelly sites", "Red, dark red, red-brown", "Moderate", "Low to moderate effective WHC", "6.5-7.8", "Low to medium", "Low to moderate", "Usually low", "N, P, Zn, B", "Excellent horticulture belt; flowering/fruit-set problems often improve with B and Zn correction plus organics."],
      ["Thally", "Ballenahalli; Chennarayanakote; Doddi; Ganganur; Jaigonahalli; Kasinaickenpatti; Kondagottlu; Makkanur; Nallur; Thally", "Vegetables, flowers, mango, minor millets, pulses", "High", "Wells, streams, check dams, localized drip", "Red loam, hill soil, lateritic/gravelly patches; variable depth", "Loam to sandy clay loam", "45-60", "15-20", "20-30", "Moderate blocky in deeper soils, crumb to loose on slopes", "Red to dark red with organic patches", "Moderate-high", "Moderate", "6.0-7.5", "Low-medium", "Moderate", "Low", "N, P, B, Zn", "Good biological activity and horticulture suitability; erosion and shallow depth matter on slopes."],
      ["Kelamangalam", "Anekollu; Thavarakarai; Udedurgam", "Mango, vegetables, flowers, pulses, millets, groundnut", "High", "Tanks, wells, some check dams; drip where available", "Red sandy loam, red loam, gravelly uplands", "Sandy loam to loam", "50-65", "12-18", "18-28", "Weak to moderate blocky", "Red, red-brown", "Moderate", "Moderate", "6.5-7.8", "Low", "Low-moderate", "Low", "N, P, Zn, B", "Strong response to organics + drip + micronutrients; moisture management is the main yield lever."],
      ["Veppanapalli", "Kannandahalli; Kollapalli; Madiyal; Thattaikaranur", "Mango, vegetables, groundnut, pulses, millets, some paddy in low-lying areas", "Moderate-High", "Tanks, wells, limited canal", "Red loam, red sandy loam, deeper clay loam in valleys", "Sandy loam to clay loam", "40-60", "15-22", "20-35", "Moderate blocky", "Red to reddish brown, darker in valleys", "Moderate", "Moderate-high in deeper soils", "6.8-8.0", "Low-medium", "Moderate", "Low-medium", "N, Zn, Fe, B", "Good mixed farming belt; both orchard expansion and resilient rainfed systems fit."],
      ["Krishnagiri", "Chitoor; Kalrayan; Pappanaickenpatti; Sigatoor; Thenkanikottai; Vattikotai", "Mango, paddy, sugarcane in irrigated pockets, vegetables, groundnut, pulses", "Moderate-High", "Canal/tank support; some borewells; drip increasing in orchards", "Red loam, deeper clay loam, some alluvial valley patches", "Loam to clay loam", "35-55", "18-25", "25-40", "Moderate to strong blocky", "Reddish brown to brown", "Moderate", "Moderate-high", "7.2-8.4", "Low-medium", "Moderate-high", "Low-medium", "N, Zn, Fe, B", "Better scope for paddy and semi-intensive crops where water is assured."],
      ["Kaveripattinam", "Agaram; Barur; Paiyur; Penneswaramadam; Santhapuram; Sundekuppam; Veeramalai", "Paddy, sugarcane, vegetables, groundnut, pulses, mango", "Moderate", "Canal + tank + wells; good water access", "Deeper red loams, clay loams, alluvial/vandal soils in valleys", "Loam to clay loam", "30-50", "18-28", "28-42", "Moderate-strong blocky", "Brown to reddish brown", "Moderate", "High", "7.0-8.2", "Low-medium", "Moderate-high", "Medium in some low-lying areas", "N, Zn, Fe", "Strong irrigated-crop base; nutrient lock-up in clay needs attention."],
      ["Uthangarai", "Bairapuram; Denkankottai area villages; Marupalli; Sondekuppam", "Millets, pulses, groundnut, some mango, limited vegetables", "Low-Moderate", "Rainfed-dominant; limited well support", "Red sandy loam, gravelly uplands, shallow soils on slopes", "Sandy loam to loam", "55-70", "10-18", "15-25", "Weak blocky, sometimes loose", "Red, light red", "Moderate-high", "Low", "6.5-7.5", "Low", "Low", "Low", "N, P, Zn, B", "Rainfed millet-pulse-groundnut belt; orchard expansion potential in places."],
      ["Bargur", "Achamangalam; Kandhikuppam; Mallapadi; Shoolamalai; Thogarapalli", "Ragi, horse gram, red gram, groundnut, mango, some vegetables", "Low", "Mostly rainfed; scattered wells/tanks", "Red loam, red sandy loam, upland gravelly soils", "Sandy loam to loam", "50-65", "12-18", "18-28", "Weak blocky", "Red to red-brown", "Moderate", "Low-moderate", "6.3-7.5", "Low", "Low", "Low", "N, P, Zn, B", "Dryland millet-pulse-groundnut cluster with mango orchard belt."],
      ["Mathur", "Mathur; Nalagampalli; Ondikottai; Pappireddihalli; Veppalampatti", "Ragi, pulses, groundnut, millets, mango", "Low-Moderate", "Rainfed-dominant; limited tank/well support", "Red sandy loam, gravelly red soils, shallow patches", "Sandy loam to loam", "55-70", "10-18", "15-25", "Weak blocky", "Red to light red", "Moderate-high", "Low", "6.5-7.5", "Low", "Low", "Low", "N, P, Zn, B", "Rainfed smallholder area; orchard and resilient dryland system focus."],
    ],
  },
  "cluster-master": {
    title: "Cluster_Master",
    description: "Krishnagiri true village cluster map master. Clustering is by production system, soil behavior, irrigation logic, crop pattern, and agri-input business relevance.",
    headers: ["Cluster", "Micro-cluster label", "District logic", "Soil logic", "Irrigation logic", "Dominant crops", "Key risks", "Priority input categories", "Crop diversity score", "Input intensity score", "Irrigation security score", "Market access score", "Soil constraint score", "Nutrient risk score"],
    rows: [
      ["Urban_Horticulture_Belt", "Urban-linked vegetable-flower cluster", "Hosur urban influence, market-linked peri-urban horticulture", "Red sandy loam / red loam; quick-draining; fertigation responsive", "Borewell + well + farm pond + drip", "Vegetables, flowers, banana, fodder, mango", "Water quality shift, high nutrient mining, labour and market volatility", "WSF, micronutrients, biostimulants, crop protection, drip accessories", "5", "5", "4", "5", "3", "4"],
      ["Flower_Vegetable_Intensive_Belt", "Intensive flower and vegetable production cluster", "Hosur–Shoolagiri commercial horticulture strip", "Red loam to gravelly red loam; moderate WHC, recurrent micronutrient demand", "Borewell/open well with drip and micro-irrigation", "Tomato, beans, cabbage, flowers, vegetables, mango", "Thrips/mites/disease pressure, price crash, nutrient imbalance", "Crop protection, WSF, Ca-B, Zn-B, adjuvants, biostimulants", "5", "5", "4", "4", "3", "5"],
      ["Highland_Horticulture_Belt", "High-elevation horticulture and cool-belt cluster", "Thally highlands and adjoining elevated belts", "Red loam, hill soil, lateritic/gravelly patches; variable depth", "Wells, streams, check dams, localized drip", "Vegetables, flowers, mango, minor millets, pulses", "Erosion, shallow depth, uneven irrigation, weather variability", "Water-solubles, micronutrients, organics, soil conditioners, fungicides/insecticides", "4", "4", "3", "3", "4", "4"],
      ["Mango_Orchard_Belt", "Mango-dominant orchard cluster with dryland intercrop", "Krishnagiri, Veppanapalli, parts of Kelamangalam", "Red loam, gravelly uplands, moderate WHC, orchard-suitable", "Tanks, wells, limited drip; mostly rainfed orchards", "Mango, pulses, groundnut, millets", "Orchard management gaps, irregular water, pest/disease in fruit-set", "Micronutrients, orchard nutrition, bio-stimulants, drip inputs, selective crop protection", "3", "3", "2", "3", "3", "4"],
      ["Mixed_Dryland_Belt", "Rainfed millet-pulse-groundnut cluster", "Uthangarai, Bargur, parts of Mathur", "Red sandy loam, gravelly uplands, shallow soils", "Rainfed-dominant; scattered wells/tanks", "Ragi, pulses, groundnut, millets", "Drought, low market access, limited input intensity", "Basal fertilizers, seed treatment, micronutrients, herbicides", "3", "2", "1", "2", "4", "3"],
      ["Irrigated_Valley_Mixed_Belt", "Irrigated paddy-mixed crop cluster", "Kaveripattinam and parts of Krishnagiri with canal/tank", "Deeper red loams, clay loams, alluvial valley soils", "Canal + tank + wells; good water access", "Paddy, sugarcane, vegetables, groundnut, pulses, mango", "Waterlogging in parts, alkalinity, nutrient lock-up", "Basal + water-solubles, micronutrients, crop protection, herbicides", "4", "4", "4", "4", "3", "4"],
    ],
  },
  "cluster-opportunity": {
    title: "Cluster_Opportunity",
    description: "Cluster-level scoring and business strategy for Krishnagiri village belts.",
    headers: ["Cluster", "No. of villages mapped", "Crop diversity score", "Input intensity score", "Irrigation security score", "Market access score", "Soil constraint score", "Nutrient risk score", "IGIM opportunity index", "Risk-adjusted opportunity", "Recommended business model", "Priority portfolio"],
    rows: [
      ["Urban_Horticulture_Belt", "8", "5", "5", "4", "5", "3", "4", "4.7", "4", "High-frequency advisory-led dealer model", "WSF, micronutrients, biostimulants, crop protection, drip accessories"],
      ["Flower_Vegetable_Intensive_Belt", "6", "5", "5", "4", "4", "3", "5", "4.7", "4", "High-frequency advisory-led dealer model", "Crop protection, WSF, Ca-B, Zn-B, adjuvants, biostimulants"],
      ["Highland_Horticulture_Belt", "10", "4", "4", "3", "3", "4", "4", "3.7", "2.7", "Specialty horticulture + micro-irrigation support model", "Water-solubles, micronutrients, organics, soil conditioners, fungicides/insecticides"],
      ["Mango_Orchard_Belt", "18", "3", "3", "2", "3", "3", "4", "3", "2.3", "Seasonal orchard campaign + micronutrient focus", "Micronutrients, orchard nutrition, bio-stimulants, drip inputs, selective crop protection"],
      ["Mixed_Dryland_Belt", "18", "3", "2", "1", "2", "4", "3", "2.2", "1.2", "Rainfed value-volume model with selective premium upsell", "Basal fertilizers, seed treatment, micronutrients, herbicides"],
      ["Irrigated_Valley_Mixed_Belt", "12", "4", "4", "4", "4", "3", "4", "4.2", "3.2", "Balanced paddy + horticulture portfolio model", "Basal + water-solubles, micronutrients, crop protection, herbicides"],
    ],
  },
  "cluster-product-priority": {
    title: "Cluster_Product_Priority",
    description: "Krishnagiri cluster-wise priority product matrix for stocking, campaigns, and dealer focus",
    headers: ["Cluster", "Basal fertilizers", "Water-soluble fertilizers", "Micronutrients", "Secondary nutrients", "Biostimulants", "Insecticides", "Fungicides", "Herbicides", "Adjuvants", "Drip / fertigation", "Seed treatment", "Priority score", "Recommended portfolio model"],
    rows: [
      ["Urban_Horticulture_Belt", "3", "5", "5", "4", "5", "5", "4", "2", "5", "5", "2", "4.3", "Premium horticulture full-stack"],
      ["Flower_Vegetable_Intensive_Belt", "3", "5", "5", "4", "5", "5", "5", "2", "5", "5", "2", "4.4", "High-frequency crop protection + WSF"],
      ["Highland_Horticulture_Belt", "3", "4", "4", "4", "4", "4", "4", "2", "3", "4", "2", "3.7", "Specialty cool-belt balanced stack"],
      ["Mango_Orchard_Belt", "3", "3", "5", "3", "4", "3", "3", "1", "4", "4", "1", "3.3", "Seasonal orchard campaign portfolio"],
      ["Mixed_Dryland_Belt", "4", "1", "3", "3", "2", "2", "2", "4", "1", "1", "4", "2.4", "Value-volume dryland essentials"],
      ["Irrigated_Valley_Mixed_Belt", "5", "4", "5", "4", "4", "4", "4", "4", "3", "4", "2", "4.2", "Balanced paddy + horticulture portfolio"],
    ],
  },
  "crop-cluster-matrix": {
    title: "Crop_Cluster_Matrix",
    description: "Krishnagiri crop-cluster matrix: crop fit, input demand, risk, and product priority by practical village cluster",
    headers: ["Crop group", "Botanical name / type", "Cluster", "Fit class", "Season / crop window", "Water need score (1-5)", "Nutrient demand score (1-5)", "Pest pressure score (1-5)", "Repeat purchase score (1-5)", "Portfolio breadth score (1-5)", "Cluster opportunity driver", "Priority product buckets", "Input intensity index", "Risk-adjusted business score", "Core selling logic", "Notes"],
    rows: [
      ["Tomato", "Solanum lycopersicum", "Urban_Horticulture_Belt", "High", "Year-round with irrigation; peak cool-season planning", "5", "5", "5", "5", "5", "Peri-urban market access + drip fertigation + frequent sprays", "WSF, Ca, B, Zn, insecticides, fungicides, adjuvants, biostimulants", "5", "4", "Strong stocking priority and repeat campaign", "Cluster-level planning generalization for IGIM use"],
      ["Tomato", "Solanum lycopersicum", "Flower_Vegetable_Intensive_Belt", "Very High", "Main commercial vegetable windows", "5", "5", "5", "5", "5", "Commercial intensive vegetable belt with repeat input demand", "WSF, Ca-B, Zn-B, fungicides, thrips/mites control, adjuvants", "5", "4", "Push premium + full protection + advisory", "Cluster-level planning generalization for IGIM use"],
      ["Tomato", "Solanum lycopersicum", "Highland_Horticulture_Belt", "High", "Cool-belt windows", "4", "5", "4", "4", "4", "Weather advantage for quality produce but irrigation uneven", "WSF, micronutrients, fungicides, bio-stimulants", "4.3", "3.5", "Strong stocking priority and repeat campaign", "Cluster-level planning generalization for IGIM use"],
      ["Beans", "Phaseolus vulgaris", "Flower_Vegetable_Intensive_Belt", "Very High", "Main vegetable windows", "4", "4", "4", "4", "4", "High repeat + quick turnover + campaign linkage", "WSF, Ca-B, Zn-B, insecticides, fungicides", "4.2", "3.5", "Push premium + full protection + advisory", "Cluster-level planning generalization for IGIM use"],
      ["Beans", "Phaseolus vulgaris", "Highland_Horticulture_Belt", "High", "Cool-belt windows", "4", "4", "3", "4", "4", "Weather advantage for quality produce", "WSF, micronutrients, fungicides", "3.8", "3", "Strong stocking priority and repeat campaign", "Cluster-level planning generalization for IGIM use"],
      ["Flowers", "Mixed cut/loose flower types", "Urban_Horticulture_Belt", "Very High", "Year-round with peak festival windows", "5", "5", "5", "5", "5", "High urban demand + frequent spray + fertigation", "WSF, Ca-B, Zn-B, insecticides, fungicides, adjuvants, biostimulants", "5", "4", "Push premium + full protection + advisory", "Cluster-level planning generalization for IGIM use"],
      ["Flowers", "Mixed cut/loose flower types", "Flower_Vegetable_Intensive_Belt", "Very High", "Year-round with peak festival windows", "5", "5", "5", "5", "5", "Commercial flower belt with high input intensity", "WSF, Ca-B, Zn-B, insecticides, fungicides, adjuvants", "5", "4", "Push premium + full protection + advisory", "Cluster-level planning generalization for IGIM use"],
      ["Mango", "Mangifera indica", "Mango_Orchard_Belt", "Very High", "Pre-flowering to harvest (Nov-Jun)", "3", "4", "4", "3", "4", "Core orchard cluster with seasonal campaign", "Micronutrients, biostimulants, fungicides, insecticides", "3.5", "2.5", "Seasonal orchard campaign", "Cluster-level planning generalization for IGIM use"],
      ["Mango", "Mangifera indica", "Urban_Horticulture_Belt", "High", "Pre-flowering to harvest (Nov-Jun)", "3", "4", "4", "3", "4", "Mixed horticulture with mango orchard component", "Micronutrients, biostimulants, fungicides, insecticides", "3.5", "2.5", "Seasonal orchard campaign", "Cluster-level planning generalization for IGIM use"],
      ["Paddy", "Oryza sativa", "Irrigated_Valley_Mixed_Belt", "Very High", "Kharif and Rabi where water assured", "5", "5", "4", "4", "4", "Canal/tank supported intensive paddy", "Basal fertilizers, WSF top-dress, herbicides, insecticides", "4.5", "3.5", "Balanced dealer + campaign model", "Cluster-level planning generalization for IGIM use"],
      ["Groundnut", "Arachis hypogaea", "Mixed_Dryland_Belt", "High", "Rainfed kharif + summer where irrigated", "3", "3", "3", "3", "3", "Dryland pulse-oilseed combination", "Basal fertilizers, seed treatment, micronutrients", "3", "2", "Value-volume dryland essentials", "Cluster-level planning generalization for IGIM use"],
      ["Millets", "Ragi/Finger millet, etc.", "Mixed_Dryland_Belt", "Very High", "Kharif rainfed", "2", "2", "2", "2", "2", "Core dryland staple with low input", "Basal fertilizers, seed treatment", "2", "1.5", "Value-volume dryland essentials", "Cluster-level planning generalization for IGIM use"],
      ["Pulses", "Various (red gram, horse gram, etc.)", "Mixed_Dryland_Belt", "Very High", "Kharif and rabi rainfed", "2", "2", "2", "2", "2", "Core dryland protein crop", "Basal fertilizers, seed treatment, micronutrients", "2.2", "1.5", "Value-volume dryland essentials", "Cluster-level planning generalization for IGIM use"],
      ["Cabbage/Brassicas", "Brassica oleracea", "Flower_Vegetable_Intensive_Belt", "High", "Cool-season windows", "4", "4", "4", "4", "4", "Commercial vegetable belt", "WSF, Ca-B, insecticides, fungicides", "4", "3", "Strong stocking priority and repeat campaign", "Cluster-level planning generalization for IGIM use"],
      ["Banana", "Musa spp.", "Urban_Horticulture_Belt", "High", "Year-round planting", "5", "5", "4", "4", "4", "Urban-linked intensive banana", "WSF, micronutrients, biostimulants, insecticides", "4.5", "3.5", "Strong stocking priority and repeat campaign", "Cluster-level planning generalization for IGIM use"],
    ],
  },
  "crop-cluster-summary": {
    title: "Crop_Cluster_Summary",
    description: "Krishnagiri crop-cluster summary dashboard for commercial focus",
    headers: ["Cluster", "No. of mapped villages", "Dominant crops", "Top product buckets", "Best commercial crop groups", "Avg input intensity", "Avg risk-adjusted business score", "Top channel strategy", "Priority season/campaign", "Remarks"],
    rows: [
      ["Urban_Horticulture_Belt", "8", "Vegetables, flowers, banana, mango", "WSF, micronutrients, crop protection, drip accessories", "Tomato, flowers, mixed vegetables", "4.4", "3.5", "Advisory-led premium dealer", "Round-year + flush campaigns", "Fast-repeat, high-service cluster"],
      ["Flower_Vegetable_Intensive_Belt", "6", "Tomato, beans, brassicas, flowers", "Crop protection, WSF, Ca-B, Zn-B, adjuvants", "Tomato, flowers, beans, cabbage", "4.5", "3.6", "Campaign + technical sales", "Peak vegetable + flower windows", "Highest crop-protection pull"],
      ["Highland_Horticulture_Belt", "10", "Vegetables, flowers, mango, pulses", "WSF, micronutrients, organics, fungicides", "Beans, brassicas, flowers", "3.9", "3.2", "Specialty horticulture support", "Cool-belt windows", "Quality-focused, moderate market access"],
      ["Mango_Orchard_Belt", "18", "Mango, pulses, millets, groundnut", "Micronutrients, orchard nutrition, biostimulants", "Mango, intercrop pulses, groundnut", "2.7", "2.2", "Seasonal orchard campaign", "Pre-flowering to fruit development", "Seasonal but strategic cluster"],
      ["Mixed_Dryland_Belt", "18", "Ragi, pulses, groundnut, millets", "Basal fertilizers, seed treatment, herbicides", "Millets, pulses, groundnut", "2.7", "2.2", "Value-volume dealer model", "Rainfed pattam season", "Large coverage, lower ticket size"],
      ["Irrigated_Valley_Mixed_Belt", "12", "Paddy, sugarcane, vegetables, groundnut", "Basal + water-solubles, micronutrients, crop protection", "Paddy, vegetables, groundnut", "3.8", "3.0", "Balanced dealer + campaign model", "Multiple crop windows", "Balanced irrigated mixed farming"],
    ],
  },
  "igim-scoring": {
    title: "IGIM_Scoring",
    description: "Formula-based IGIM scoring: higher soil/nutrient scores mean higher constraint/risk.",
    headers: ["Block", "Crop diversity score", "Horticulture score", "Irrigation security score", "Market access score", "Soil constraint score", "Nutrient risk score", "Input intensity score", "Dealer opportunity index", "Priority category", "Rationale"],
    rows: [
      ["Hosur", "3", "5", "4", "5", "2.5", "4", "4.4", "3.9", "Tier 2 – Strong mixed opportunity", "Fast-draining, fertigation-responsive, highly suitable for vegetables/flowers but needs split nutrition and micronutrient correction."],
      ["Shoolagiri", "4", "5", "3.5", "5", "2.5", "4", "4.5", "4", "Tier 2 – Strong mixed opportunity", "Excellent horticulture belt; flowering/fruit-set problems often improve with B and Zn correction plus organics."],
      ["Thally", "3", "4", "3.5", "4", "3", "4", "3.7", "3.3", "Tier 3 – Selective / crop-specific opportunity", "Good biological activity and horticulture suitability; erosion and shallow depth matter on slopes."],
      ["Kelamangalam", "3", "4", "3.5", "4", "3", "4", "3.7", "3.3", "Tier 3 – Selective / crop-specific opportunity", "Strong response to organics + drip + micronutrients; moisture management is the main yield lever."],
      ["Veppanapalli", "3", "3.5", "3.5", "3", "3", "4", "3.3", "3.1", "Tier 3 – Selective / crop-specific opportunity", "Good mixed farming belt; both orchard expansion and resilient rainfed systems fit."],
      ["Krishnagiri", "2", "4", "4", "4", "3", "4.5", "3.6", "3.2", "Tier 3 – Selective / crop-specific opportunity", "Better scope for paddy and semi-intensive crops where water is assured."],
      ["Kaveripattinam", "3", "3", "4", "3.5", "3.5", "4", "3.5", "3.4", "Tier 3 – Selective / crop-specific opportunity", "Strong irrigated-crop base; nutrient lock-up in clay needs attention."],
      ["Uthangarai", "2", "2", "2", "2", "3", "3", "2", "2", "Tier 4 – Rainfed / value volume focus", "Rainfed millet-pulse-groundnut belt; orchard expansion potential in places."],
      ["Bargur", "2", "1.5", "1.5", "2", "3.5", "3", "1.8", "1.8", "Tier 4 – Rainfed / value volume focus", "Dryland millet-pulse-groundnut cluster with mango orchard belt."],
      ["Mathur", "2", "2", "2", "2", "3", "3", "2", "2", "Tier 4 – Rainfed / value volume focus", "Rainfed smallholder area; orchard and resilient dryland system focus."],
    ],
  },
  "cluster-map-view": {
    title: "Cluster_Map_View",
    description: "Krishnagiri cluster view by block. This is a planning map, not a GIS polygon map.",
    headers: ["Block", "Main cluster", "Secondary pattern", "Representative villages in main cluster", "Core crops", "Core soils", "Opportunity tier", "Planning note"],
    rows: [
      ["Bargur", "Mixed_Dryland_Belt", "Mango_Orchard_Belt", "Achamangalam, Kandhikuppam, Mallapadi, Shoolamalai, Thogarapalli", "Ragi, horse gram, red gram, groundnut, mango, some vegetables", "Red loam, red sandy loam, upland gravelly soils", "Tier 3", "Bargur is primarily a rainfed millet-pulse-groundnut cluster with mango orchard belt."],
      ["Hosur", "Urban_Horticulture_Belt", "Irrigated_Valley_Mixed_Belt", "Achettipalli, Bagaloor, Belathur, Chennasandiram, Onnalvadi, Thorapalli Agraharam, Thummanapalli", "Vegetables, flowers, mango, fodder, banana, some maize and pulses", "Red sandy loam, red loam, gravelly upland soils", "Tier 1", "Hosur is primarily a urban-linked vegetable-flower cluster with irrigated valley mixed belt."],
      ["Kaveripattinam", "Irrigated_Valley_Mixed_Belt", "", "Agaram, Barur, Paiyur, Penneswaramadam, Santhapuram, Sundekuppam, Veeramalai", "Paddy, sugarcane in suitable irrigated pockets, vegetables, groundnut, pulses, mango", "Deeper red loams, clay loams, alluvial/vandal valley soils", "Tier 2", "Kaveripattinam is primarily a deeper-soil irrigated paddy-mixed crop cluster with limited secondary variation."],
      ["Kelamangalam", "Highland_Horticulture_Belt", "Mango_Orchard_Belt", "Anekollu, Thavarakarai, Udedurgam", "Mango, vegetables, flowers, pulses, millets, groundnut", "Red sandy loam, red loam, gravelly uplands", "Tier 2", "Kelamangalam is primarily a high-elevation horticulture and cool-belt cluster with mango orchard belt."],
      ["Krishnagiri", "Mango_Orchard_Belt", "Irrigated_Valley_Mixed_Belt", "Chitoor, Kalrayan, Pappanaickenpatti, Sigatoor, Thenkanikottai, Vattikotai", "Mango, paddy, sugarcane in irrigated pockets, vegetables, groundnut, pulses", "Red loam, deeper clay loam, some alluvial valley patches", "Tier 2", "Krishnagiri is primarily a mango orchard cluster with irrigated valley mixed belt support."],
      ["Mathur", "Mixed_Dryland_Belt", "Mango_Orchard_Belt", "Mathur, Nalagampalli, Ondikottai, Pappireddihalli, Veppalampatti", "Ragi, pulses, groundnut, millets, mango", "Red sandy loam, gravelly red soils, shallow patches", "Tier 3", "Mathur is primarily a rainfed millet-pulse-groundnut cluster with mango orchard belt."],
      ["Shoolagiri", "Flower_Vegetable_Intensive_Belt", "Urban_Horticulture_Belt", "Athimugam, Berigai, Kumbalam, Marandapalli, Pannapalli, Shoolagiri, Uddanapalli", "Tomato, beans, cabbage, flowers, mango, pulses, maize in irrigated pockets", "Red sandy loam, red loam, gravelly red uplands, some lateritic influence", "Tier 1", "Shoolagiri is primarily a intensive flower and vegetable production cluster with urban horticulture influence."],
      ["Thally", "Highland_Horticulture_Belt", "Mixed_Dryland_Belt", "Ballenahalli, Chennarayanakote, Doddi, Ganganur, Jaigonahalli, Kasinaickenpatti, Kondagottlu, Makkanur, Nallur, Thally", "Vegetables, flowers, mango, minor millets, pulses", "Red loam, hill soil, lateritic/gravelly patches; variable depth", "Tier 2", "Thally is primarily a high-elevation horticulture and cool-belt cluster with mixed dryland influence."],
      ["Uthangarai", "Mixed_Dryland_Belt", "Mango_Orchard_Belt", "Bairapuram, Denkankottai area villages, Marupalli, Sondekuppam", "Millets, pulses, groundnut, some mango, limited vegetables", "Red sandy loam, gravelly uplands, shallow soils on slopes", "Tier 3", "Uthangarai is primarily a rainfed millet-pulse-groundnut cluster with mango orchard potential."],
      ["Veppanapalli", "Mango_Orchard_Belt", "Highland_Horticulture_Belt", "Kannandahalli, Kollapalli, Madiyal, Thattaikaranur", "Mango, vegetables, groundnut, pulses, millets, some paddy in low-lying areas", "Red loam, red sandy loam, deeper clay loam in valleys", "Tier 2", "Veppanapalli is primarily a mango orchard cluster with highland horticulture influence."],
    ],
  },
  "soil-guide": {
    title: "Soil_Guide",
    description: "Dominant soil-group guide used to interpret Krishnagiri block soils.",
    headers: ["Soil group", "Approx sand %", "Approx silt %", "Approx clay %", "Structure", "Color", "Porosity", "Water-holding capacity", "Typical pH", "Organic matter", "CEC", "Salinity tendency", "Typical deficiencies", "Interpretation"],
    rows: [
      ["Red sandy loam", "55-70", "10-20", "15-25", "Weak granular to weak sub-angular blocky", "Red to reddish brown", "Moderate-high", "Low-moderate", "6.5-7.8", "Low", "Low-moderate", "Low", "N, P, Zn, B", "Fast-draining; best for groundnut, vegetables, flowers, mango under drip and split nutrition"],
      ["Red loam", "45-60", "10-20", "20-30", "Sub-angular blocky", "Red to red-brown", "Moderate", "Moderate", "6.8-8.0", "Low-medium", "Moderate", "Low", "N, P, Zn, B", "Versatile soil for millets, pulses, maize, mango, vegetables"],
      ["Gravelly upland red soil", "45-60 + gravel", "10-15", "20-30", "Weak blocky / loose", "Dark red / brown", "Moderate but low effective storage", "Low-effective", "5.8-7.5", "Low-medium", "Low", "Very low", "N, P, B, Zn", "Shallow rooting; orchard and hardy crop fit better than water-heavy crops"],
      ["Clay loam / clay pockets", "20-35", "20-30", "35-45", "Moderate to strong blocky", "Reddish brown to dark brown", "Moderate", "Moderate-high to high", "7.2-8.4", "Low-medium", "Moderate-high", "Low-medium in poor drainage", "N, Zn, Fe, B", "Better for paddy/intensive irrigation but watch alkalinity and drainage"],
      ["Lateritic / hill-influenced soil", "45-60", "10-20", "20-30", "Crumb to weak blocky", "Red / dark red", "Moderate-high", "Low-moderate", "5.5-7.0", "Low-medium", "Low-moderate", "Very low", "N, P, K, B, Zn, sometimes Ca", "Good biological activity; erosion and depth are main risks"],
    ],
  },
  "sources": {
    title: "Sources",
    description: "This reference sheet has been removed from the staff-facing portal.",
    headers: [],
    rows: [],
  },
  "village-refs": {
    title: "Village_Refs",
    description: "This reference sheet has been removed from the staff-facing portal.",
    headers: [],
    rows: [],
  },
};
