export const villageMasterData = {
  title: "Village_Master",
  description: "Village-wise planning sheet for Krishnagiri. Values are inherited block-level generalizations for representative villages, not lab-test substitutes.",
  headers: ["Block", "Village", "Village coverage type", "Village profile tag", "Major crops / business focus", "Horticulture strength", "Irrigation pattern", "Dominant soil groups", "Texture class", "Approx sand %", "Approx silt %", "Approx clay %", "Structure", "Color", "Porosity", "Water-holding capacity", "pH", "Organic matter", "CEC", "Salinity", "Soil nutrient deficiencies", "Practical village note", "Inherited block rationale"],
  rows: [
    ["Hosur", "Achettipalli", "Representative village planning row", "Urban-linked horticulture / vegetables / flowers", "Vegetables, flowers, mango, fodder, banana, some maize and pulses", "Very High", "Open wells, borewells, farm ponds, some tank support", "Red sandy loam, red loam, gravelly upland soils", "Sandy loam to red loam", "55-70", "10-20", "15-25", "Weak granular to sub-angular blocky", "Red to reddish brown", "Moderate to high", "Low to moderate", "6.8-7.8", "Low to medium", "Low to moderate", "Usually low inland", "N, P, Zn, B; Fe in calcareous/alkaline pockets", "Representative village row for planning.", "Inherited from Hosur block."],
    ["Hosur", "Bagaloor", "Representative village planning row", "Urban-linked horticulture / vegetables / flowers", "Vegetables, flowers, mango, fodder, banana, some maize and pulses", "Very High", "Open wells, borewells, farm ponds, some tank support", "Red sandy loam, red loam, gravelly upland soils", "Sandy loam to red loam", "55-70", "10-20", "15-25", "Weak granular to sub-angular blocky", "Red to reddish brown", "Moderate to high", "Low to moderate", "6.8-7.8", "Low to medium", "Low to moderate", "Usually low inland", "N, P, Zn, B; Fe in calcareous/alkaline pockets", "Representative village row for planning.", "Inherited from Hosur block."],
    ["Hosur", "Belathur", "Representative village planning row", "Urban-linked horticulture / vegetables / flowers", "Vegetables, flowers, mango, fodder, banana, some maize and pulses", "Very High", "Open wells, borewells, farm ponds, some tank support", "Red sandy loam, red loam, gravelly upland soils", "Sandy loam to red loam", "55-70", "10-20", "15-25", "Weak granular to sub-angular blocky", "Red to reddish brown", "Moderate to high", "Low to moderate", "6.8-7.8", "Low to medium", "Low to moderate", "Usually low inland", "N, P, Zn, B; Fe in calcareous/alkaline pockets", "Representative village row for planning.", "Inherited from Hosur block."],
    ["Hosur", "Chennasandiram", "Representative village planning row", "Horticulture + mixed farming", "Vegetables, flowers, mango, fodder, banana, some maize and pulses", "Very High", "Open wells, borewells, farm ponds, some tank support", "Red sandy loam, red loam, gravelly upland soils", "Sandy loam to red loam", "55-70", "10-20", "15-25", "Weak granular to sub-angular blocky", "Red to reddish brown", "Moderate to high", "Low to moderate", "6.8-7.8", "Low to medium", "Low to moderate", "Usually low inland", "N, P, Zn, B; Fe in calcareous/alkaline pockets", "Representative village row for planning.", "Inherited from Hosur block."],
    ["Hosur", "Kelavarapalli", "Representative village planning row", "Urban-linked horticulture / vegetables / flowers", "Vegetables, flowers, mango, fodder, banana, some maize and pulses", "Very High", "Open wells, borewells, farm ponds, some tank support", "Red sandy loam, red loam, gravelly upland soils", "Sandy loam to red loam", "55-70", "10-20", "15-25", "Weak granular to sub-angular blocky", "Red to reddish brown", "Moderate to high", "Low to moderate", "6.8-7.8", "Low to medium", "Low to moderate", "Usually low inland", "N, P, Zn, B; Fe in calcareous/alkaline pockets", "Representative village row for planning.", "Inherited from Hosur block."],
    ["Hosur", "Onnalvadi", "Representative village planning row", "Urban-linked horticulture / vegetables / flowers", "Vegetables, flowers, mango, fodder, banana, some maize and pulses", "Very High", "Open wells, borewells, farm ponds, some tank support", "Red sandy loam, red loam, gravelly upland soils", "Sandy loam to red loam", "55-70", "10-20", "15-25", "Weak granular to sub-angular blocky", "Red to reddish brown", "Moderate to high", "Low to moderate", "6.8-7.8", "Low to medium", "Low to moderate", "Usually low inland", "N, P, Zn, B; Fe in calcareous/alkaline pockets", "Representative village row for planning.", "Inherited from Hosur block."],
    ["Hosur", "Thorapalli Agraharam", "Representative village planning row", "Urban-linked horticulture / vegetables / flowers", "Vegetables, flowers, mango, fodder, banana, some maize and pulses", "Very High", "Open wells, borewells, farm ponds, some tank support", "Red sandy loam, red loam, gravelly upland soils", "Sandy loam to red loam", "55-70", "10-20", "15-25", "Weak granular to sub-angular blocky", "Red to reddish brown", "Moderate to high", "Low to moderate", "6.8-7.8", "Low to medium", "Low to moderate", "Usually low inland", "N, P, Zn, B; Fe in calcareous/alkaline pockets", "Representative village row for planning.", "Inherited from Hosur block."],
    ["Hosur", "Thummanapalli", "Representative village planning row", "Urban-linked horticulture / vegetables / flowers", "Vegetables, flowers, mango, fodder, banana, some maize and pulses", "Very High", "Open wells, borewells, farm ponds, some tank support", "Red sandy loam, red loam, gravelly upland soils", "Sandy loam to red loam", "55-70", "10-20", "15-25", "Weak granular to sub-angular blocky", "Red to reddish brown", "Moderate to high", "Low to moderate", "6.8-7.8", "Low to medium", "Low to moderate", "Usually low inland", "N, P, Zn, B; Fe in calcareous/alkaline pockets", "Representative village row for planning.", "Inherited from Hosur block."],
    ["Shoolagiri", "Athimugam", "Representative village planning row", "Intensive vegetable/flower production", "Tomato, beans, cabbage, flowers, mango, pulses, maize", "Very High", "Borewells/open wells with supplemental tank water", "Red sandy loam, red loam, gravelly red uplands", "Sandy loam to loam", "55-68", "10-18", "18-27", "Weak blocky; loose in gravelly sites", "Red, dark red, red-brown", "Moderate", "Low to moderate effective WHC", "6.5-7.8", "Low to medium", "Low to moderate", "Usually low", "N, P, Zn, B", "Excellent horticulture belt.", "Inherited from Shoolagiri block."],
    ["Shoolagiri", "Berigai", "Representative village planning row", "Intensive vegetable/flower production", "Tomato, beans, cabbage, flowers, mango, pulses, maize", "Very High", "Borewells/open wells with supplemental tank water", "Red sandy loam, red loam, gravelly red uplands", "Sandy loam to loam", "55-68", "10-18", "18-27", "Weak blocky; loose in gravelly sites", "Red, dark red, red-brown", "Moderate", "Low to moderate effective WHC", "6.5-7.8", "Low to medium", "Low to moderate", "Usually low", "N, P, Zn, B", "Excellent horticulture belt.", "Inherited from Shoolagiri block."],
    ["Shoolagiri", "Kumbalam", "Representative village planning row", "Intensive vegetable/flower production", "Tomato, beans, cabbage, flowers, mango, pulses, maize", "Very High", "Borewells/open wells with supplemental tank water", "Red sandy loam, red loam, gravelly red uplands", "Sandy loam to loam", "55-68", "10-18", "18-27", "Weak blocky; loose in gravelly sites", "Red, dark red, red-brown", "Moderate", "Low to moderate effective WHC", "6.5-7.8", "Low to medium", "Low to moderate", "Usually low", "N, P, Zn, B", "Excellent horticulture belt.", "Inherited from Shoolagiri block."],
    ["Shoolagiri", "Marandapalli", "Representative village planning row", "Intensive vegetable/flower production", "Tomato, beans, cabbage, flowers, mango, pulses, maize", "Very High", "Borewells/open wells with supplemental tank water", "Red sandy loam, red loam, gravelly red uplands", "Sandy loam to loam", "55-68", "10-18", "18-27", "Weak blocky; loose in gravelly sites", "Red, dark red, red-brown", "Moderate", "Low to moderate effective WHC", "6.5-7.8", "Low to medium", "Low to moderate", "Usually low", "N, P, Zn, B", "Excellent horticulture belt.", "Inherited from Shoolagiri block."],
    ["Shoolagiri", "Pannapalli", "Representative village planning row", "Intensive vegetable/flower production", "Tomato, beans, cabbage, flowers, mango, pulses, maize", "Very High", "Borewells/open wells with supplemental tank water", "Red sandy loam, red loam, gravelly red uplands", "Sandy loam to loam", "55-68", "10-18", "18-27", "Weak blocky; loose in gravelly sites", "Red, dark red, red-brown", "Moderate", "Low to moderate effective WHC", "6.5-7.8", "Low to medium", "Low to moderate", "Usually low", "N, P, Zn, B", "Excellent horticulture belt.", "Inherited from Shoolagiri block."],
    ["Shoolagiri", "Shoolagiri", "Representative village planning row", "Intensive vegetable/flower production", "Tomato, beans, cabbage, flowers, mango, pulses, maize", "Very High", "Borewells/open wells with supplemental tank water", "Red sandy loam, red loam, gravelly red uplands", "Sandy loam to loam", "55-68", "10-18", "18-27", "Weak blocky; loose in gravelly sites", "Red, dark red, red-brown", "Moderate", "Low to moderate effective WHC", "6.5-7.8", "Low to medium", "Low to moderate", "Usually low", "N, P, Zn, B", "Excellent horticulture belt.", "Inherited from Shoolagiri block."],
    ["Shoolagiri", "Uddanapalli", "Representative village planning row", "Intensive vegetable/flower production", "Tomato, beans, cabbage, flowers, mango, pulses, maize", "Very High", "Borewells/open wells with supplemental tank water", "Red sandy loam, red loam, gravelly red uplands", "Sandy loam to loam", "55-68", "10-18", "18-27", "Weak blocky; loose in gravelly sites", "Red, dark red, red-brown", "Moderate", "Low to moderate effective WHC", "6.5-7.8", "Low to medium", "Low to moderate", "Usually low", "N, P, Zn, B", "Excellent horticulture belt.", "Inherited from Shoolagiri block."],
    ["Thally", "Ballenahalli", "Representative village planning row", "Highland horticulture", "Vegetables, flowers, mango, minor millets, pulses", "High", "Wells, streams, check dams, localized drip", "Red loam, hill soil, lateritic/gravelly patches", "Loam to sandy clay loam", "45-60", "15-20", "20-30", "Moderate blocky", "Red to dark red", "Moderate-high", "Moderate", "6.0-7.5", "Low-medium", "Moderate", "Low", "N, P, B, Zn", "Good biological activity.", "Inherited from Thally block."],
    ["Thally", "Chennarayanakote", "Representative village planning row", "Highland horticulture", "Vegetables, flowers, mango, minor millets, pulses", "High", "Wells, streams, check dams, localized drip", "Red loam, hill soil, lateritic/gravelly patches", "Loam to sandy clay loam", "45-60", "15-20", "20-30", "Moderate blocky", "Red to dark red", "Moderate-high", "Moderate", "6.0-7.5", "Low-medium", "Moderate", "Low", "N, P, B, Zn", "Good biological activity.", "Inherited from Thally block."],
    ["Thally", "Doddi", "Representative village planning row", "Highland horticulture", "Vegetables, flowers, mango, minor millets, pulses", "High", "Wells, streams, check dams, localized drip", "Red loam, hill soil, lateritic/gravelly patches", "Loam to sandy clay loam", "45-60", "15-20", "20-30", "Moderate blocky", "Red to dark red", "Moderate-high", "Moderate", "6.0-7.5", "Low-medium", "Moderate", "Low", "N, P, B, Zn", "Good biological activity.", "Inherited from Thally block."],
    ["Thally", "Ganganur", "Representative village planning row", "Highland horticulture", "Vegetables, flowers, mango, minor millets, pulses", "High", "Wells, streams, check dams, localized drip", "Red loam, hill soil, lateritic/gravelly patches", "Loam to sandy clay loam", "45-60", "15-20", "20-30", "Moderate blocky", "Red to dark red", "Moderate-high", "Moderate", "6.0-7.5", "Low-medium", "Moderate", "Low", "N, P, B, Zn", "Good biological activity.", "Inherited from Thally block."],
    ["Thally", "Jaigonahalli", "Representative village planning row", "Highland horticulture", "Vegetables, flowers, mango, minor millets, pulses", "High", "Wells, streams, check dams, localized drip", "Red loam, hill soil, lateritic/gravelly patches", "Loam to sandy clay loam", "45-60", "15-20", "20-30", "Moderate blocky", "Red to dark red", "Moderate-high", "Moderate", "6.0-7.5", "Low-medium", "Moderate", "Low", "N, P, B, Zn", "Good biological activity.", "Inherited from Thally block."],
    ["Thally", "Kasinaickenpatti", "Representative village planning row", "Highland horticulture", "Vegetables, flowers, mango, minor millets, pulses", "High", "Wells, streams, check dams, localized drip", "Red loam, hill soil, lateritic/gravelly patches", "Loam to sandy clay loam", "45-60", "15-20", "20-30", "Moderate blocky", "Red to dark red", "Moderate-high", "Moderate", "6.0-7.5", "Low-medium", "Moderate", "Low", "N, P, B, Zn", "Good biological activity.", "Inherited from Thally block."],
    ["Thally", "Kondagottlu", "Representative village planning row", "Highland horticulture", "Vegetables, flowers, mango, minor millets, pulses", "High", "Wells, streams, check dams, localized drip", "Red loam, hill soil, lateritic/gravelly patches", "Loam to sandy clay loam", "45-60", "15-20", "20-30", "Moderate blocky", "Red to dark red", "Moderate-high", "Moderate", "6.0-7.5", "Low-medium", "Moderate", "Low", "N, P, B, Zn", "Good biological activity.", "Inherited from Thally block."],
    ["Thally", "Makkanur", "Representative village planning row", "Highland horticulture", "Vegetables, flowers, mango, minor millets, pulses", "High", "Wells, streams, check dams, localized drip", "Red loam, hill soil, lateritic/gravelly patches", "Loam to sandy clay loam", "45-60", "15-20", "20-30", "Moderate blocky", "Red to dark red", "Moderate-high", "Moderate", "6.0-7.5", "Low-medium", "Moderate", "Low", "N, P, B, Zn", "Good biological activity.", "Inherited from Thally block."],
    ["Thally", "Nallur", "Representative village planning row", "Highland horticulture", "Vegetables, flowers, mango, minor millets, pulses", "High", "Wells, streams, check dams, localized drip", "Red loam, hill soil, lateritic/gravelly patches", "Loam to sandy clay loam", "45-60", "15-20", "20-30", "Moderate blocky", "Red to dark red", "Moderate-high", "Moderate", "6.0-7.5", "Low-medium", "Moderate", "Low", "N, P, B, Zn", "Good biological activity.", "Inherited from Thally block."],
    ["Thally", "Thally", "Representative village planning row", "Highland horticulture", "Vegetables, flowers, mango, minor millets, pulses", "High", "Wells, streams, check dams, localized drip", "Red loam, hill soil, lateritic/gravelly patches", "Loam to sandy clay loam", "45-60", "15-20", "20-30", "Moderate blocky", "Red to dark red", "Moderate-high", "Moderate", "6.0-7.5", "Low-medium", "Moderate", "Low", "N, P, B, Zn", "Good biological activity.", "Inherited from Thally block."],
    ["Kelamangalam", "Anekollu", "Representative village planning row", "Mango + horticulture", "Mango, vegetables, flowers, pulses, millets, groundnut", "High", "Tanks, wells, some check dams; drip where available", "Red sandy loam, red loam, gravelly uplands", "Sandy loam to loam", "50-65", "12-18", "18-28", "Weak to moderate blocky", "Red, red-brown", "Moderate", "Moderate", "6.5-7.8", "Low", "Low-moderate", "Low", "N, P, Zn, B", "Strong response to organics + drip.", "Inherited from Kelamangalam block."],
    ["Kelamangalam", "Thavarakarai", "Representative village planning row", "Mango + horticulture", "Mango, vegetables, flowers, pulses, millets, groundnut", "High", "Tanks, wells, some check dams; drip where available", "Red sandy loam, red loam, gravelly uplands", "Sandy loam to loam", "50-65", "12-18", "18-28", "Weak to moderate blocky", "Red, red-brown", "Moderate", "Moderate", "6.5-7.8", "Low", "Low-moderate", "Low", "N, P, Zn, B", "Strong response to organics + drip.", "Inherited from Kelamangalam block."],
    ["Kelamangalam", "Udedurgam", "Representative village planning row", "Mango + horticulture", "Mango, vegetables, flowers, pulses, millets, groundnut", "High", "Tanks, wells, some check dams; drip where available", "Red sandy loam, red loam, gravelly uplands", "Sandy loam to loam", "50-65", "12-18", "18-28", "Weak to moderate blocky", "Red, red-brown", "Moderate", "Moderate", "6.5-7.8", "Low", "Low-moderate", "Low", "N, P, Zn, B", "Strong response to organics + drip.", "Inherited from Kelamangalam block."],
    ["Veppanapalli", "Kannandahalli", "Representative village planning row", "Mango + mixed farming", "Mango, vegetables, groundnut, pulses, millets", "Moderate-High", "Tanks, wells, limited canal", "Red loam, red sandy loam, deeper clay loam in valleys", "Sandy loam to clay loam", "40-60", "15-22", "20-35", "Moderate blocky", "Red to reddish brown", "Moderate", "Moderate-high in deeper soils", "6.8-8.0", "Low-medium", "Moderate", "Low-medium", "N, Zn, Fe, B", "Good mixed farming belt.", "Inherited from Veppanapalli block."],
    ["Veppanapalli", "Kollapalli", "Representative village planning row", "Mango + mixed farming", "Mango, vegetables, groundnut, pulses, millets", "Moderate-High", "Tanks, wells, limited canal", "Red loam, red sandy loam, deeper clay loam in valleys", "Sandy loam to clay loam", "40-60", "15-22", "20-35", "Moderate blocky", "Red to reddish brown", "Moderate", "Moderate-high in deeper soils", "6.8-8.0", "Low-medium", "Moderate", "Low-medium", "N, Zn, Fe, B", "Good mixed farming belt.", "Inherited from Veppanapalli block."],
    ["Veppanapalli", "Madiyal", "Representative village planning row", "Mango + mixed farming", "Mango, vegetables, groundnut, pulses, millets", "Moderate-High", "Tanks, wells, limited canal", "Red loam, red sandy loam, deeper clay loam in valleys", "Sandy loam to clay loam", "40-60", "15-22", "20-35", "Moderate blocky", "Red to reddish brown", "Moderate", "Moderate-high in deeper soils", "6.8-8.0", "Low-medium", "Moderate", "Low-medium", "N, Zn, Fe, B", "Good mixed farming belt.", "Inherited from Veppanapalli block."],
    ["Veppanapalli", "Thattaikaranur", "Representative village planning row", "Mango + mixed farming", "Mango, vegetables, groundnut, pulses, millets", "Moderate-High", "Tanks, wells, limited canal", "Red loam, red sandy loam, deeper clay loam in valleys", "Sandy loam to clay loam", "40-60", "15-22", "20-35", "Moderate blocky", "Red to reddish brown", "Moderate", "Moderate-high in deeper soils", "6.8-8.0", "Low-medium", "Moderate", "Low-medium", "N, Zn, Fe, B", "Good mixed farming belt.", "Inherited from Veppanapalli block."],
    ["Krishnagiri", "Chitoor", "Representative village planning row", "Mango + irrigated mixed", "Mango, paddy, sugarcane, vegetables, groundnut, pulses", "Moderate-High", "Canal/tank support; some borewells; drip increasing", "Red loam, deeper clay loam, some alluvial valley patches", "Loam to clay loam", "35-55", "18-25", "25-40", "Moderate to strong blocky", "Reddish brown to brown", "Moderate", "Moderate-high", "7.2-8.4", "Low-medium", "Moderate-high", "Low-medium", "N, Zn, Fe, B", "Better scope for paddy.", "Inherited from Krishnagiri block."],
    ["Krishnagiri", "Kalrayan", "Representative village planning row", "Mango + irrigated mixed", "Mango, paddy, sugarcane, vegetables, groundnut, pulses", "Moderate-High", "Canal/tank support; some borewells; drip increasing", "Red loam, deeper clay loam, some alluvial valley patches", "Loam to clay loam", "35-55", "18-25", "25-40", "Moderate to strong blocky", "Reddish brown to brown", "Moderate", "Moderate-high", "7.2-8.4", "Low-medium", "Moderate-high", "Low-medium", "N, Zn, Fe, B", "Better scope for paddy.", "Inherited from Krishnagiri block."],
    ["Krishnagiri", "Pappanaickenpatti", "Representative village planning row", "Mango + irrigated mixed", "Mango, paddy, sugarcane, vegetables, groundnut, pulses", "Moderate-High", "Canal/tank support; some borewells; drip increasing", "Red loam, deeper clay loam, some alluvial valley patches", "Loam to clay loam", "35-55", "18-25", "25-40", "Moderate to strong blocky", "Reddish brown to brown", "Moderate", "Moderate-high", "7.2-8.4", "Low-medium", "Moderate-high", "Low-medium", "N, Zn, Fe, B", "Better scope for paddy.", "Inherited from Krishnagiri block."],
    ["Krishnagiri", "Sigatoor", "Representative village planning row", "Mango + irrigated mixed", "Mango, paddy, sugarcane, vegetables, groundnut, pulses", "Moderate-High", "Canal/tank support; some borewells; drip increasing", "Red loam, deeper clay loam, some alluvial valley patches", "Loam to clay loam", "35-55", "18-25", "25-40", "Moderate to strong blocky", "Reddish brown to brown", "Moderate", "Moderate-high", "7.2-8.4", "Low-medium", "Moderate-high", "Low-medium", "N, Zn, Fe, B", "Better scope for paddy.", "Inherited from Krishnagiri block."],
    ["Krishnagiri", "Thenkanikottai", "Representative village planning row", "Mango + irrigated mixed", "Mango, paddy, sugarcane, vegetables, groundnut, pulses", "Moderate-High", "Canal/tank support; some borewells; drip increasing", "Red loam, deeper clay loam, some alluvial valley patches", "Loam to clay loam", "35-55", "18-25", "25-40", "Moderate to strong blocky", "Reddish brown to brown", "Moderate", "Moderate-high", "7.2-8.4", "Low-medium", "Moderate-high", "Low-medium", "N, Zn, Fe, B", "Better scope for paddy.", "Inherited from Krishnagiri block."],
    ["Krishnagiri", "Vattikotai", "Representative village planning row", "Mango + irrigated mixed", "Mango, paddy, sugarcane, vegetables, groundnut, pulses", "Moderate-High", "Canal/tank support; some borewells; drip increasing", "Red loam, deeper clay loam, some alluvial valley patches", "Loam to clay loam", "35-55", "18-25", "25-40", "Moderate to strong blocky", "Reddish brown to brown", "Moderate", "Moderate-high", "7.2-8.4", "Low-medium", "Moderate-high", "Low-medium", "N, Zn, Fe, B", "Better scope for paddy.", "Inherited from Krishnagiri block."],
    ["Kaveripattinam", "Agaram", "Representative village planning row", "Irrigated paddy-mixed", "Paddy, sugarcane, vegetables, groundnut, pulses, mango", "Moderate", "Canal + tank + wells; good water access", "Deeper red loams, clay loams, alluvial/vandal soils", "Loam to clay loam", "30-50", "18-28", "28-42", "Moderate-strong blocky", "Brown to reddish brown", "Moderate", "High", "7.0-8.2", "Low-medium", "Moderate-high", "Medium in low-lying areas", "N, Zn, Fe", "Strong irrigated-crop base.", "Inherited from Kaveripattinam block."],
    ["Kaveripattinam", "Barur", "Representative village planning row", "Irrigated paddy-mixed", "Paddy, sugarcane, vegetables, groundnut, pulses, mango", "Moderate", "Canal + tank + wells; good water access", "Deeper red loams, clay loams, alluvial/vandal soils", "Loam to clay loam", "30-50", "18-28", "28-42", "Moderate-strong blocky", "Brown to reddish brown", "Moderate", "High", "7.0-8.2", "Low-medium", "Moderate-high", "Medium in low-lying areas", "N, Zn, Fe", "Strong irrigated-crop base.", "Inherited from Kaveripattinam block."],
    ["Kaveripattinam", "Paiyur", "Representative village planning row", "Irrigated paddy-mixed", "Paddy, sugarcane, vegetables, groundnut, pulses, mango", "Moderate", "Canal + tank + wells; good water access", "Deeper red loams, clay loams, alluvial/vandal soils", "Loam to clay loam", "30-50", "18-28", "28-42", "Moderate-strong blocky", "Brown to reddish brown", "Moderate", "High", "7.0-8.2", "Low-medium", "Moderate-high", "Medium in low-lying areas", "N, Zn, Fe", "Strong irrigated-crop base.", "Inherited from Kaveripattinam block."],
    ["Kaveripattinam", "Penneswaramadam", "Representative village planning row", "Irrigated paddy-mixed", "Paddy, sugarcane, vegetables, groundnut, pulses, mango", "Moderate", "Canal + tank + wells; good water access", "Deeper red loams, clay loams, alluvial/vandal soils", "Loam to clay loam", "30-50", "18-28", "28-42", "Moderate-strong blocky", "Brown to reddish brown", "Moderate", "High", "7.0-8.2", "Low-medium", "Moderate-high", "Medium in low-lying areas", "N, Zn, Fe", "Strong irrigated-crop base.", "Inherited from Kaveripattinam block."],
    ["Kaveripattinam", "Santhapuram", "Representative village planning row", "Irrigated paddy-mixed", "Paddy, sugarcane, vegetables, groundnut, pulses, mango", "Moderate", "Canal + tank + wells; good water access", "Deeper red loams, clay loams, alluvial/vandal soils", "Loam to clay loam", "30-50", "18-28", "28-42", "Moderate-strong blocky", "Brown to reddish brown", "Moderate", "High", "7.0-8.2", "Low-medium", "Moderate-high", "Medium in low-lying areas", "N, Zn, Fe", "Strong irrigated-crop base.", "Inherited from Kaveripattinam block."],
    ["Kaveripattinam", "Sundekuppam", "Representative village planning row", "Irrigated paddy-mixed", "Paddy, sugarcane, vegetables, groundnut, pulses, mango", "Moderate", "Canal + tank + wells; good water access", "Deeper red loams, clay loams, alluvial/vandal soils", "Loam to clay loam", "30-50", "18-28", "28-42", "Moderate-strong blocky", "Brown to reddish brown", "Moderate", "High", "7.0-8.2", "Low-medium", "Moderate-high", "Medium in low-lying areas", "N, Zn, Fe", "Strong irrigated-crop base.", "Inherited from Kaveripattinam block."],
    ["Kaveripattinam", "Veeramalai", "Representative village planning row", "Irrigated paddy-mixed", "Paddy, sugarcane, vegetables, groundnut, pulses, mango", "Moderate", "Canal + tank + wells; good water access", "Deeper red loams, clay loams, alluvial/vandal soils", "Loam to clay loam", "30-50", "18-28", "28-42", "Moderate-strong blocky", "Brown to reddish brown", "Moderate", "High", "7.0-8.2", "Low-medium", "Moderate-high", "Medium in low-lying areas", "N, Zn, Fe", "Strong irrigated-crop base.", "Inherited from Kaveripattinam block."],
    ["Uthangarai", "Bairapuram", "Representative village planning row", "Rainfed dryland", "Millets, pulses, groundnut, some mango", "Low-Moderate", "Rainfed-dominant; limited well support", "Red sandy loam, gravelly uplands, shallow soils", "Sandy loam to loam", "55-70", "10-18", "15-25", "Weak blocky, sometimes loose", "Red, light red", "Moderate-high", "Low", "6.5-7.5", "Low", "Low", "Low", "N, P, Zn, B", "Rainfed millet-pulse-groundnut belt.", "Inherited from Uthangarai block."],
    ["Uthangarai", "Denkankottai area villages", "Representative village planning row", "Rainfed dryland", "Millets, pulses, groundnut, some mango", "Low-Moderate", "Rainfed-dominant; limited well support", "Red sandy loam, gravelly uplands, shallow soils", "Sandy loam to loam", "55-70", "10-18", "15-25", "Weak blocky, sometimes loose", "Red, light red", "Moderate-high", "Low", "6.5-7.5", "Low", "Low", "Low", "N, P, Zn, B", "Rainfed millet-pulse-groundnut belt.", "Inherited from Uthangarai block."],
    ["Uthangarai", "Marupalli", "Representative village planning row", "Rainfed dryland", "Millets, pulses, groundnut, some mango", "Low-Moderate", "Rainfed-dominant; limited well support", "Red sandy loam, gravelly uplands, shallow soils", "Sandy loam to loam", "55-70", "10-18", "15-25", "Weak blocky, sometimes loose", "Red, light red", "Moderate-high", "Low", "6.5-7.5", "Low", "Low", "Low", "N, P, Zn, B", "Rainfed millet-pulse-groundnut belt.", "Inherited from Uthangarai block."],
    ["Uthangarai", "Sondekuppam", "Representative village planning row", "Rainfed dryland", "Millets, pulses, groundnut, some mango", "Low-Moderate", "Rainfed-dominant; limited well support", "Red sandy loam, gravelly uplands, shallow soils", "Sandy loam to loam", "55-70", "10-18", "15-25", "Weak blocky, sometimes loose", "Red, light red", "Moderate-high", "Low", "6.5-7.5", "Low", "Low", "Low", "N, P, Zn, B", "Rainfed millet-pulse-groundnut belt.", "Inherited from Uthangarai block."],
    ["Bargur", "Achamangalam", "Representative village planning row", "Rainfed dryland", "Ragi, horse gram, red gram, groundnut, mango", "Low", "Mostly rainfed; scattered wells/tanks", "Red loam, red sandy loam, upland gravelly soils", "Sandy loam to loam", "50-65", "12-18", "18-28", "Weak blocky", "Red to red-brown", "Moderate", "Low-moderate", "6.3-7.5", "Low", "Low", "Low", "N, P, Zn, B", "Dryland millet-pulse-groundnut cluster.", "Inherited from Bargur block."],
    ["Bargur", "Kandhikuppam", "Representative village planning row", "Rainfed dryland", "Ragi, horse gram, red gram, groundnut, mango", "Low", "Mostly rainfed; scattered wells/tanks", "Red loam, red sandy loam, upland gravelly soils", "Sandy loam to loam", "50-65", "12-18", "18-28", "Weak blocky", "Red to red-brown", "Moderate", "Low-moderate", "6.3-7.5", "Low", "Low", "Low", "N, P, Zn, B", "Dryland millet-pulse-groundnut cluster.", "Inherited from Bargur block."],
    ["Bargur", "Mallapadi", "Representative village planning row", "Rainfed dryland", "Ragi, horse gram, red gram, groundnut, mango", "Low", "Mostly rainfed; scattered wells/tanks", "Red loam, red sandy loam, upland gravelly soils", "Sandy loam to loam", "50-65", "12-18", "18-28", "Weak blocky", "Red to red-brown", "Moderate", "Low-moderate", "6.3-7.5", "Low", "Low", "Low", "N, P, Zn, B", "Dryland millet-pulse-groundnut cluster.", "Inherited from Bargur block."],
    ["Bargur", "Shoolamalai", "Representative village planning row", "Rainfed dryland", "Ragi, horse gram, red gram, groundnut, mango", "Low", "Mostly rainfed; scattered wells/tanks", "Red loam, red sandy loam, upland gravelly soils", "Sandy loam to loam", "50-65", "12-18", "18-28", "Weak blocky", "Red to red-brown", "Moderate", "Low-moderate", "6.3-7.5", "Low", "Low", "Low", "N, P, Zn, B", "Dryland millet-pulse-groundnut cluster.", "Inherited from Bargur block."],
    ["Bargur", "Thogarapalli", "Representative village planning row", "Rainfed dryland", "Ragi, horse gram, red gram, groundnut, mango", "Low", "Mostly rainfed; scattered wells/tanks", "Red loam, red sandy loam, upland gravelly soils", "Sandy loam to loam", "50-65", "12-18", "18-28", "Weak blocky", "Red to red-brown", "Moderate", "Low-moderate", "6.3-7.5", "Low", "Low", "Low", "N, P, Zn, B", "Dryland millet-pulse-groundnut cluster.", "Inherited from Bargur block."],
    ["Mathur", "Mathur", "Representative village planning row", "Rainfed dryland", "Ragi, pulses, groundnut, millets, mango", "Low-Moderate", "Rainfed-dominant; limited tank/well support", "Red sandy loam, gravelly red soils, shallow patches", "Sandy loam to loam", "55-70", "10-18", "15-25", "Weak blocky", "Red to light red", "Moderate-high", "Low", "6.5-7.5", "Low", "Low", "Low", "N, P, Zn, B", "Rainfed smallholder area.", "Inherited from Mathur block."],
    ["Mathur", "Nalagampalli", "Representative village planning row", "Rainfed dryland", "Ragi, pulses, groundnut, millets, mango", "Low-Moderate", "Rainfed-dominant; limited tank/well support", "Red sandy loam, gravelly red soils, shallow patches", "Sandy loam to loam", "55-70", "10-18", "15-25", "Weak blocky", "Red to light red", "Moderate-high", "Low", "6.5-7.5", "Low", "Low", "Low", "N, P, Zn, B", "Rainfed smallholder area.", "Inherited from Mathur block."],
    ["Mathur", "Ondikottai", "Representative village planning row", "Rainfed dryland", "Ragi, pulses, groundnut, millets, mango", "Low-Moderate", "Rainfed-dominant; limited tank/well support", "Red sandy loam, gravelly red soils, shallow patches", "Sandy loam to loam", "55-70", "10-18", "15-25", "Weak blocky", "Red to light red", "Moderate-high", "Low", "6.5-7.5", "Low", "Low", "Low", "N, P, Zn, B", "Rainfed smallholder area.", "Inherited from Mathur block."],
    ["Mathur", "Pappireddihalli", "Representative village planning row", "Rainfed dryland", "Ragi, pulses, groundnut, millets, mango", "Low-Moderate", "Rainfed-dominant; limited tank/well support", "Red sandy loam, gravelly red soils, shallow patches", "Sandy loam to loam", "55-70", "10-18", "15-25", "Weak blocky", "Red to light red", "Moderate-high", "Low", "6.5-7.5", "Low", "Low", "Low", "N, P, Zn, B", "Rainfed smallholder area.", "Inherited from Mathur block."],
    ["Mathur", "Veppalampatti", "Representative village planning row", "Rainfed dryland", "Ragi, pulses, groundnut, millets, mango", "Low-Moderate", "Rainfed-dominant; limited tank/well support", "Red sandy loam, gravelly red soils, shallow patches", "Sandy loam to loam", "55-70", "10-18", "15-25", "Weak blocky", "Red to light red", "Moderate-high", "Low", "6.5-7.5", "Low", "Low", "Low", "N, P, Zn, B", "Rainfed smallholder area.", "Inherited from Mathur block."],
  ],
};

export const villageClusterMapData = {
  title: "Village_Cluster_Map",
  description: "Krishnagiri village cluster map. Villages are clustered into real planning belts.",
  headers: ["Block", "Village", "Primary cluster", "Micro-cluster label", "Why this cluster fits", "Market linkage", "Dominant crop system", "Soil behavior", "Water source logic", "pH tendency", "WHC tendency", "Major deficiency risk", "Pest-pressure tendency", "Input-demand intensity", "Dealer opportunity", "Suggested portfolio focus", "Suggested advisory theme", "Source inheritance"],
  rows: villageMasterData.rows.map((row) => {
    const block = row[0];
    const village = row[1];
    const profileTag = row[3];
    const crops = row[4];
    const soilGroups = row[7];
    const irrigation = row[6];
    const pH = row[16];
    const whc = row[15];
    const deficiencies = row[20];
    
    let cluster = "Mixed_Dryland_Belt";
    let microLabel = "Rainfed millet-pulse-groundnut cluster";
    
    if (block === "Hosur") {
      cluster = "Urban_Horticulture_Belt";
      microLabel = "Urban-linked vegetable-flower cluster";
    } else if (block === "Shoolagiri") {
      cluster = "Flower_Vegetable_Intensive_Belt";
      microLabel = "Intensive flower and vegetable production cluster";
    } else if (block === "Thally") {
      cluster = "Highland_Horticulture_Belt";
      microLabel = "High-elevation horticulture and cool-belt cluster";
    } else if (block === "Kelamangalam" || block === "Veppanapalli" || block === "Krishnagiri") {
      cluster = "Mango_Orchard_Belt";
      microLabel = "Mango-dominant orchard cluster";
    } else if (block === "Kaveripattinam") {
      cluster = "Irrigated_Valley_Mixed_Belt";
      microLabel = "Irrigated paddy-mixed crop cluster";
    }
    
    const marketLinkage = cluster.includes("Urban") || cluster.includes("Flower") ? "High urban/market linkage" : cluster.includes("Highland") ? "Moderate market linkage" : "Low-moderate market linkage";
    const pestPressure = cluster.includes("Horticulture") || cluster.includes("Flower") ? "High thrips/mites/disease pressure" : "Moderate pest pressure";
    const inputIntensity = cluster.includes("Urban") || cluster.includes("Flower") ? "Very High" : cluster.includes("Highland") || cluster.includes("Irrigated") ? "High" : "Moderate";
    const dealerOpp = cluster.includes("Urban") || cluster.includes("Flower") ? "Very High" : cluster.includes("Highland") || cluster.includes("Irrigated") ? "High" : "Moderate";
    const portfolio = cluster.includes("Urban") || cluster.includes("Flower") ? "WSF, micronutrients, biostimulants, crop protection, drip accessories" : cluster.includes("Mango") ? "Micronutrients, orchard nutrition, biostimulants" : "Basal fertilizers, seed treatment, micronutrients";
    const advisory = cluster.includes("Horticulture") ? "Fertigation scheduling + crop protection rotation" : cluster.includes("Mango") ? "Orchard management + micronutrient correction" : "Soil health + water management";
    
    return [
      block,
      village,
      cluster,
      microLabel,
      `${block} village grouped under ${microLabel} because of its dominant crop business system.`,
      marketLinkage,
      crops,
      soilGroups,
      irrigation,
      pH,
      whc,
      deficiencies,
      pestPressure,
      inputIntensity,
      dealerOpp,
      portfolio,
      advisory,
      `Inherited from ${block} block.`,
    ];
  }),
};

export const villageScoringData = {
  title: "Village_Scoring",
  description: "Village-level IGIM scoring for representative Krishnagiri villages.",
  headers: ["Block", "Village", "Village profile tag", "Crop diversity score", "Horticulture score", "Irrigation security score", "Market access score", "Soil constraint score", "Nutrient risk score", "Input intensity score", "Dealer opportunity index", "Priority category", "Suggested portfolio focus", "Scoring note"],
  rows: villageMasterData.rows.map((row) => {
    const block = row[0];
    const village = row[1];
    const profileTag = row[3];
    
    let scores = {
      cropDiversity: "3",
      horticulture: "3",
      irrigation: "3",
      market: "3",
      soilConstraint: "3",
      nutrientRisk: "3",
      inputIntensity: "3",
      dealerOpp: "3",
      tier: "Tier 3 – Selective / crop-specific opportunity",
      portfolio: "Basal fertilizers, seed treatment, micronutrients",
    };
    
    if (block === "Hosur") {
      scores = { cropDiversity: "3", horticulture: "5", irrigation: "4", market: "5", soilConstraint: "2.5", nutrientRisk: "4", inputIntensity: "4.4", dealerOpp: "3.9", tier: "Tier 2 – Strong mixed opportunity", portfolio: "WSF + micronutrients + crop protection + adjuvants + biostimulants" };
    } else if (block === "Shoolagiri") {
      scores = { cropDiversity: "4", horticulture: "5", irrigation: "3.5", market: "5", soilConstraint: "2.5", nutrientRisk: "4", inputIntensity: "4.5", dealerOpp: "4", tier: "Tier 2 – Strong mixed opportunity", portfolio: "WSF + micronutrients + crop protection + adjuvants + biostimulants" };
    } else if (block === "Thally") {
      scores = { cropDiversity: "3", horticulture: "4", irrigation: "3.5", market: "4", soilConstraint: "3", nutrientRisk: "4", inputIntensity: "3.7", dealerOpp: "3.3", tier: "Tier 3 – Selective / crop-specific opportunity", portfolio: "WSF + micronutrients + organics + fungicides" };
    } else if (block === "Kelamangalam") {
      scores = { cropDiversity: "3", horticulture: "4", irrigation: "3.5", market: "4", soilConstraint: "3", nutrientRisk: "4", inputIntensity: "3.7", dealerOpp: "3.3", tier: "Tier 3 – Selective / crop-specific opportunity", portfolio: "Micronutrients + orchard nutrition + biostimulants" };
    } else if (block === "Veppanapalli") {
      scores = { cropDiversity: "3", horticulture: "3.5", irrigation: "3.5", market: "3", soilConstraint: "3", nutrientRisk: "4", inputIntensity: "3.3", dealerOpp: "3.1", tier: "Tier 3 – Selective / crop-specific opportunity", portfolio: "Micronutrients + orchard nutrition + biostimulants" };
    } else if (block === "Krishnagiri") {
      scores = { cropDiversity: "2", horticulture: "4", irrigation: "4", market: "4", soilConstraint: "3", nutrientRisk: "4.5", inputIntensity: "3.6", dealerOpp: "3.2", tier: "Tier 3 – Selective / crop-specific opportunity", portfolio: "Micronutrients + orchard nutrition + basal fertilizers" };
    } else if (block === "Kaveripattinam") {
      scores = { cropDiversity: "3", horticulture: "3", irrigation: "4", market: "3.5", soilConstraint: "3.5", nutrientRisk: "4", inputIntensity: "3.5", dealerOpp: "3.4", tier: "Tier 3 – Selective / crop-specific opportunity", portfolio: "Basal + WSF + micronutrients + crop protection" };
    } else if (block === "Uthangarai" || block === "Bargur" || block === "Mathur") {
      scores = { cropDiversity: "2", horticulture: "2", irrigation: "2", market: "2", soilConstraint: "3", nutrientRisk: "3", inputIntensity: "2", dealerOpp: "2", tier: "Tier 4 – Rainfed / value volume focus", portfolio: "Basal fertilizers + seed treatment + micronutrients" };
    }
    
    return [
      block,
      village,
      profileTag,
      scores.cropDiversity,
      scores.horticulture,
      scores.irrigation,
      scores.market,
      scores.soilConstraint,
      scores.nutrientRisk,
      scores.inputIntensity,
      scores.dealerOpp,
      scores.tier,
      scores.portfolio,
      "Inherited from block scoring with light village-profile adjustment.",
    ];
  }),
};
